//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.account;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class AutoDownloadSettings extends TlObject {

    public static final int ID = 1674235686;

    public TlObject low;
	public TlObject medium;
	public TlObject high;

    public AutoDownloadSettings(TlObject low, TlObject medium, TlObject high) {
        this.low = low;
		this.medium = medium;
		this.high = high;
    }

    public static AutoDownloadSettings read(ByteArrayInputStream bytes) throws IOException {
        TlObject low = TlObject.read(bytes);
		TlObject medium = TlObject.read(bytes);
		TlObject high = TlObject.read(bytes);
		
		return new AutoDownloadSettings(low, medium, high);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.low.write());
		bOut.write(this.medium.write());
		bOut.write(this.high.write());
		
		return bOut.toByteArray();
    }
}
