//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.account;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class AutoSaveSettings extends TlObject {

    public static final int ID = 1279133341;

    public TlObject users_settings;
	public TlObject chats_settings;
	public TlObject broadcasts_settings;
	public ArrayList<TlObject> exceptions;
	public ArrayList<TlObject> chats;
	public ArrayList<TlObject> users;

    public AutoSaveSettings(TlObject users_settings, TlObject chats_settings, TlObject broadcasts_settings, ArrayList<TlObject> exceptions, ArrayList<TlObject> chats, ArrayList<TlObject> users) {
        this.users_settings = users_settings;
		this.chats_settings = chats_settings;
		this.broadcasts_settings = broadcasts_settings;
		this.exceptions = exceptions;
		this.chats = chats;
		this.users = users;
    }

    public static AutoSaveSettings read(ByteArrayInputStream bytes) throws IOException {
        TlObject users_settings = TlObject.read(bytes);
		TlObject chats_settings = TlObject.read(bytes);
		TlObject broadcasts_settings = TlObject.read(bytes);
		ArrayList<TlObject> exceptions = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		ArrayList<TlObject> chats = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		ArrayList<TlObject> users = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		
		return new AutoSaveSettings(users_settings, chats_settings, broadcasts_settings, exceptions, chats, users);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.users_settings.write());
		bOut.write(this.chats_settings.write());
		bOut.write(this.broadcasts_settings.write());
		bOut.write(new VectorPrimitive(this.exceptions).write());
		bOut.write(new VectorPrimitive(this.chats).write());
		bOut.write(new VectorPrimitive(this.users).write());
		
		return bOut.toByteArray();
    }
}
