//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class BotApp extends TlObject {

    public static final int ID = -347034123;

    public boolean inactive;
	public boolean request_write_access;
	public TlObject app;

    public BotApp(boolean inactive, boolean request_write_access, TlObject app) {
        this.inactive = inactive;
		this.request_write_access = request_write_access;
		this.app = app;
    }

    public static BotApp read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean inactive = (flags & (1 << 0)) != 0;
		boolean request_write_access = (flags & (1 << 1)) != 0;
		TlObject app = TlObject.read(bytes);
		
		return new BotApp(inactive, request_write_access, app);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.inactive ? (1 << 0) : 0;
		flags |= this.request_write_access ? (1 << 1) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(this.app.write());
		
		return bOut.toByteArray();
    }
}
