//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class BotCallbackAnswer extends TlObject {

    public static final int ID = 911761060;

    public boolean alert;
	public boolean has_url;
	public boolean native_ui;
	public String message;
	public String url;
	public int cache_time;

    public BotCallbackAnswer(boolean alert, boolean has_url, boolean native_ui, String message, String url, int cache_time) {
        this.alert = alert;
		this.has_url = has_url;
		this.native_ui = native_ui;
		this.message = message;
		this.url = url;
		this.cache_time = cache_time;
    }

    public static BotCallbackAnswer read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean alert = (flags & (1 << 1)) != 0;
		boolean has_url = (flags & (1 << 3)) != 0;
		boolean native_ui = (flags & (1 << 4)) != 0;
		String message = (flags & (1 << 0)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		String url = (flags & (1 << 2)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		int cache_time = IntPrimitive.read(bytes).getValue();
		
		return new BotCallbackAnswer(alert, has_url, native_ui, message, url, cache_time);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.alert ? (1 << 1) : 0;
		flags |= this.has_url ? (1 << 3) : 0;
		flags |= this.native_ui ? (1 << 4) : 0;
		flags |= (this.message != null) ? (1 << 0) : 0;
		flags |= (this.url != null) ? (1 << 2) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		if(this.message != null)
			bOut.write(new StringPrimitive(this.message).write());
		if(this.url != null)
			bOut.write(new StringPrimitive(this.url).write());
		bOut.write(new IntPrimitive(this.cache_time).write());
		
		return bOut.toByteArray();
    }
}
