//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class BotInlineMessageMediaVenue extends TlObject {

    public static final int ID = -1970903652;

    public TlObject geo;
	public String title;
	public String address;
	public String provider;
	public String venue_id;
	public String venue_type;
	public TlObject reply_markup;

    public BotInlineMessageMediaVenue(TlObject geo, String title, String address, String provider, String venue_id, String venue_type, TlObject reply_markup) {
        this.geo = geo;
		this.title = title;
		this.address = address;
		this.provider = provider;
		this.venue_id = venue_id;
		this.venue_type = venue_type;
		this.reply_markup = reply_markup;
    }

    public static BotInlineMessageMediaVenue read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		TlObject geo = TlObject.read(bytes);
		String title = StringPrimitive.read(bytes).getValue();
		String address = StringPrimitive.read(bytes).getValue();
		String provider = StringPrimitive.read(bytes).getValue();
		String venue_id = StringPrimitive.read(bytes).getValue();
		String venue_type = StringPrimitive.read(bytes).getValue();
		TlObject reply_markup = (flags & (1 << 2)) != 0 ?  TlObject.read(bytes) : null;
		
		return new BotInlineMessageMediaVenue(geo, title, address, provider, venue_id, venue_type, reply_markup);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= (this.reply_markup != null) ? (1 << 2) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(this.geo.write());
		bOut.write(new StringPrimitive(this.title).write());
		bOut.write(new StringPrimitive(this.address).write());
		bOut.write(new StringPrimitive(this.provider).write());
		bOut.write(new StringPrimitive(this.venue_id).write());
		bOut.write(new StringPrimitive(this.venue_type).write());
		if(this.reply_markup != null)
			bOut.write(this.reply_markup.write());
		
		return bOut.toByteArray();
    }
}
