//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.upload;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class CdnFileReuploadNeeded extends TlObject {

    public static final int ID = -290921362;

    public byte[] request_token;

    public CdnFileReuploadNeeded(byte[] request_token) {
        this.request_token = request_token;
    }

    public static CdnFileReuploadNeeded read(ByteArrayInputStream bytes) throws IOException {
        byte[] request_token = BytesPrimitive.read(bytes).getValue();
		
		return new CdnFileReuploadNeeded(request_token);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new BytesPrimitive(this.request_token).write());
		
		return bOut.toByteArray();
    }
}
