//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ChannelAdminLogEventActionToggleGroupCallSetting extends TlObject {

    public static final int ID = 1456906823;

    public TlObject join_muted;

    public ChannelAdminLogEventActionToggleGroupCallSetting(TlObject join_muted) {
        this.join_muted = join_muted;
    }

    public static ChannelAdminLogEventActionToggleGroupCallSetting read(ByteArrayInputStream bytes) throws IOException {
        TlObject join_muted = TlObject.read(bytes);
		
		return new ChannelAdminLogEventActionToggleGroupCallSetting(join_muted);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.join_muted.write());
		
		return bOut.toByteArray();
    }
}
