//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.updates;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ChannelDifferenceEmpty extends TlObject {

    public static final int ID = 1041346555;

    public boolean finalv;
	public int pts;
	public int timeout;

    public ChannelDifferenceEmpty(boolean finalv, int pts, int timeout) {
        this.finalv = finalv;
		this.pts = pts;
		this.timeout = timeout;
    }

    public static ChannelDifferenceEmpty read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean finalv = (flags & (1 << 0)) != 0;
		int pts = IntPrimitive.read(bytes).getValue();
		int timeout = (flags & (1 << 1)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		
		return new ChannelDifferenceEmpty(finalv, pts, timeout);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.finalv ? (1 << 0) : 0;
		flags |= (this.timeout != 0) ? (1 << 1) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new IntPrimitive(this.pts).write());
		if(this.timeout != 0)
			bOut.write(new IntPrimitive(this.timeout).write());
		
		return bOut.toByteArray();
    }
}
