//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ChannelAdminLogEventActionParticipantUnmute extends TlObject {

    public static final int ID = -431740480;

    public TlObject participant;

    public ChannelAdminLogEventActionParticipantUnmute(TlObject participant) {
        this.participant = participant;
    }

    public static ChannelAdminLogEventActionParticipantUnmute read(ByteArrayInputStream bytes) throws IOException {
        TlObject participant = TlObject.read(bytes);
		
		return new ChannelAdminLogEventActionParticipantUnmute(participant);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.participant.write());
		
		return bOut.toByteArray();
    }
}
