//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ChannelParticipantsMentions extends TlObject {

    public static final int ID = -531931925;

    public String q;
	public int top_msg_id;

    public ChannelParticipantsMentions(String q, int top_msg_id) {
        this.q = q;
		this.top_msg_id = top_msg_id;
    }

    public static ChannelParticipantsMentions read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		String q = (flags & (1 << 0)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		int top_msg_id = (flags & (1 << 1)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		
		return new ChannelParticipantsMentions(q, top_msg_id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= (this.q != null) ? (1 << 0) : 0;
		flags |= (this.top_msg_id != 0) ? (1 << 1) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		if(this.q != null)
			bOut.write(new StringPrimitive(this.q).write());
		if(this.top_msg_id != 0)
			bOut.write(new IntPrimitive(this.top_msg_id).write());
		
		return bOut.toByteArray();
    }
}
