//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ChannelAdminLogEventActionChangeHistoryTTL extends TlObject {

    public static final int ID = 1855199800;

    public int prev_value;
	public int new_value;

    public ChannelAdminLogEventActionChangeHistoryTTL(int prev_value, int new_value) {
        this.prev_value = prev_value;
		this.new_value = new_value;
    }

    public static ChannelAdminLogEventActionChangeHistoryTTL read(ByteArrayInputStream bytes) throws IOException {
        int prev_value = IntPrimitive.read(bytes).getValue();
		int new_value = IntPrimitive.read(bytes).getValue();
		
		return new ChannelAdminLogEventActionChangeHistoryTTL(prev_value, new_value);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new IntPrimitive(this.prev_value).write());
		bOut.write(new IntPrimitive(this.new_value).write());
		
		return bOut.toByteArray();
    }
}
