//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ChannelAdminLogEventActionChangeUsername extends TlObject {

    public static final int ID = 1783299128;

    public String prev_value;
	public String new_value;

    public ChannelAdminLogEventActionChangeUsername(String prev_value, String new_value) {
        this.prev_value = prev_value;
		this.new_value = new_value;
    }

    public static ChannelAdminLogEventActionChangeUsername read(ByteArrayInputStream bytes) throws IOException {
        String prev_value = StringPrimitive.read(bytes).getValue();
		String new_value = StringPrimitive.read(bytes).getValue();
		
		return new ChannelAdminLogEventActionChangeUsername(prev_value, new_value);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new StringPrimitive(this.prev_value).write());
		bOut.write(new StringPrimitive(this.new_value).write());
		
		return bOut.toByteArray();
    }
}
