//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ChannelAdminLogEventActionChangeLinkedChat extends TlObject {

    public static final int ID = 84703944;

    public long prev_value;
	public long new_value;

    public ChannelAdminLogEventActionChangeLinkedChat(long prev_value, long new_value) {
        this.prev_value = prev_value;
		this.new_value = new_value;
    }

    public static ChannelAdminLogEventActionChangeLinkedChat read(ByteArrayInputStream bytes) throws IOException {
        long prev_value = LongPrimitive.read(bytes).getValue();
		long new_value = LongPrimitive.read(bytes).getValue();
		
		return new ChannelAdminLogEventActionChangeLinkedChat(prev_value, new_value);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new LongPrimitive(this.prev_value).write());
		bOut.write(new LongPrimitive(this.new_value).write());
		
		return bOut.toByteArray();
    }
}
