//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class Channel extends TlObject {

    public static final int ID = -2094689180;

    public boolean creator;
	public boolean left;
	public boolean broadcast;
	public boolean verified;
	public boolean megagroup;
	public boolean restricted;
	public boolean signatures;
	public boolean min;
	public boolean scam;
	public boolean has_link;
	public boolean has_geo;
	public boolean slowmode_enabled;
	public boolean call_active;
	public boolean call_not_empty;
	public boolean fake;
	public boolean gigagroup;
	public boolean noforwards;
	public boolean join_to_send;
	public boolean join_request;
	public boolean forum;
	public long id;
	public long access_hash;
	public String title;
	public String username;
	public TlObject photo;
	public int date;
	public ArrayList<TlObject> restriction_reason;
	public TlObject admin_rights;
	public TlObject banned_rights;
	public TlObject default_banned_rights;
	public int participants_count;
	public ArrayList<TlObject> usernames;

    public Channel(boolean creator, boolean left, boolean broadcast, boolean verified, boolean megagroup, boolean restricted, boolean signatures, boolean min, boolean scam, boolean has_link, boolean has_geo, boolean slowmode_enabled, boolean call_active, boolean call_not_empty, boolean fake, boolean gigagroup, boolean noforwards, boolean join_to_send, boolean join_request, boolean forum, long id, long access_hash, String title, String username, TlObject photo, int date, ArrayList<TlObject> restriction_reason, TlObject admin_rights, TlObject banned_rights, TlObject default_banned_rights, int participants_count, ArrayList<TlObject> usernames) {
        this.creator = creator;
		this.left = left;
		this.broadcast = broadcast;
		this.verified = verified;
		this.megagroup = megagroup;
		this.restricted = restricted;
		this.signatures = signatures;
		this.min = min;
		this.scam = scam;
		this.has_link = has_link;
		this.has_geo = has_geo;
		this.slowmode_enabled = slowmode_enabled;
		this.call_active = call_active;
		this.call_not_empty = call_not_empty;
		this.fake = fake;
		this.gigagroup = gigagroup;
		this.noforwards = noforwards;
		this.join_to_send = join_to_send;
		this.join_request = join_request;
		this.forum = forum;
		this.id = id;
		this.access_hash = access_hash;
		this.title = title;
		this.username = username;
		this.photo = photo;
		this.date = date;
		this.restriction_reason = restriction_reason;
		this.admin_rights = admin_rights;
		this.banned_rights = banned_rights;
		this.default_banned_rights = default_banned_rights;
		this.participants_count = participants_count;
		this.usernames = usernames;
    }

    public static Channel read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean creator = (flags & (1 << 0)) != 0;
		boolean left = (flags & (1 << 2)) != 0;
		boolean broadcast = (flags & (1 << 5)) != 0;
		boolean verified = (flags & (1 << 7)) != 0;
		boolean megagroup = (flags & (1 << 8)) != 0;
		boolean restricted = (flags & (1 << 9)) != 0;
		boolean signatures = (flags & (1 << 11)) != 0;
		boolean min = (flags & (1 << 12)) != 0;
		boolean scam = (flags & (1 << 19)) != 0;
		boolean has_link = (flags & (1 << 20)) != 0;
		boolean has_geo = (flags & (1 << 21)) != 0;
		boolean slowmode_enabled = (flags & (1 << 22)) != 0;
		boolean call_active = (flags & (1 << 23)) != 0;
		boolean call_not_empty = (flags & (1 << 24)) != 0;
		boolean fake = (flags & (1 << 25)) != 0;
		boolean gigagroup = (flags & (1 << 26)) != 0;
		boolean noforwards = (flags & (1 << 27)) != 0;
		boolean join_to_send = (flags & (1 << 28)) != 0;
		boolean join_request = (flags & (1 << 29)) != 0;
		boolean forum = (flags & (1 << 30)) != 0;
		int flags2 = IntPrimitive.read(bytes).getValue();
		long id = LongPrimitive.read(bytes).getValue();
		long access_hash = (flags & (1 << 13)) != 0 ?  LongPrimitive.read(bytes).getValue() : 0;
		String title = StringPrimitive.read(bytes).getValue();
		String username = (flags & (1 << 6)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		TlObject photo = TlObject.read(bytes);
		int date = IntPrimitive.read(bytes).getValue();
		ArrayList<TlObject> restriction_reason = (flags & (1 << 9)) != 0 ?  ((VectorPrimitive)TlObject.read(bytes)).getValue() : null;
		TlObject admin_rights = (flags & (1 << 14)) != 0 ?  TlObject.read(bytes) : null;
		TlObject banned_rights = (flags & (1 << 15)) != 0 ?  TlObject.read(bytes) : null;
		TlObject default_banned_rights = (flags & (1 << 18)) != 0 ?  TlObject.read(bytes) : null;
		int participants_count = (flags & (1 << 17)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		ArrayList<TlObject> usernames = (flags2 & (1 << 0)) != 0 ?  ((VectorPrimitive)TlObject.read(bytes)).getValue() : null;
		
		return new Channel(creator, left, broadcast, verified, megagroup, restricted, signatures, min, scam, has_link, has_geo, slowmode_enabled, call_active, call_not_empty, fake, gigagroup, noforwards, join_to_send, join_request, forum, id, access_hash, title, username, photo, date, restriction_reason, admin_rights, banned_rights, default_banned_rights, participants_count, usernames);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.creator ? (1 << 0) : 0;
		flags |= this.left ? (1 << 2) : 0;
		flags |= this.broadcast ? (1 << 5) : 0;
		flags |= this.verified ? (1 << 7) : 0;
		flags |= this.megagroup ? (1 << 8) : 0;
		flags |= this.restricted ? (1 << 9) : 0;
		flags |= this.signatures ? (1 << 11) : 0;
		flags |= this.min ? (1 << 12) : 0;
		flags |= this.scam ? (1 << 19) : 0;
		flags |= this.has_link ? (1 << 20) : 0;
		flags |= this.has_geo ? (1 << 21) : 0;
		flags |= this.slowmode_enabled ? (1 << 22) : 0;
		flags |= this.call_active ? (1 << 23) : 0;
		flags |= this.call_not_empty ? (1 << 24) : 0;
		flags |= this.fake ? (1 << 25) : 0;
		flags |= this.gigagroup ? (1 << 26) : 0;
		flags |= this.noforwards ? (1 << 27) : 0;
		flags |= this.join_to_send ? (1 << 28) : 0;
		flags |= this.join_request ? (1 << 29) : 0;
		flags |= this.forum ? (1 << 30) : 0;
		int flags2 = 0;
		flags |= (this.access_hash != 0) ? (1 << 13) : 0;
		flags |= (this.username != null) ? (1 << 6) : 0;
		flags |= (this.restriction_reason != null) ? (1 << 9) : 0;
		flags |= (this.admin_rights != null) ? (1 << 14) : 0;
		flags |= (this.banned_rights != null) ? (1 << 15) : 0;
		flags |= (this.default_banned_rights != null) ? (1 << 18) : 0;
		flags |= (this.participants_count != 0) ? (1 << 17) : 0;
		flags2 |= (this.usernames != null) ? (1 << 0) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new IntPrimitive(flags2).write());
		bOut.write(new LongPrimitive(this.id).write());
		if(this.access_hash != 0)
			bOut.write(new LongPrimitive(this.access_hash).write());
		bOut.write(new StringPrimitive(this.title).write());
		if(this.username != null)
			bOut.write(new StringPrimitive(this.username).write());
		bOut.write(this.photo.write());
		bOut.write(new IntPrimitive(this.date).write());
		if(this.restriction_reason != null)
			bOut.write(new VectorPrimitive(this.restriction_reason).write());
		if(this.admin_rights != null)
			bOut.write(this.admin_rights.write());
		if(this.banned_rights != null)
			bOut.write(this.banned_rights.write());
		if(this.default_banned_rights != null)
			bOut.write(this.default_banned_rights.write());
		if(this.participants_count != 0)
			bOut.write(new IntPrimitive(this.participants_count).write());
		if(this.usernames != null)
			bOut.write(new VectorPrimitive(this.usernames).write());
		
		return bOut.toByteArray();
    }
}
