//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ChannelAdminLogEventActionParticipantJoinByRequest extends TlObject {

    public static final int ID = -1347021750;

    public TlObject invite;
	public long approved_by;

    public ChannelAdminLogEventActionParticipantJoinByRequest(TlObject invite, long approved_by) {
        this.invite = invite;
		this.approved_by = approved_by;
    }

    public static ChannelAdminLogEventActionParticipantJoinByRequest read(ByteArrayInputStream bytes) throws IOException {
        TlObject invite = TlObject.read(bytes);
		long approved_by = LongPrimitive.read(bytes).getValue();
		
		return new ChannelAdminLogEventActionParticipantJoinByRequest(invite, approved_by);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.invite.write());
		bOut.write(new LongPrimitive(this.approved_by).write());
		
		return bOut.toByteArray();
    }
}
