//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ChatReactionsSome extends TlObject {

    public static final int ID = 1713193015;

    public ArrayList<TlObject> reactions;

    public ChatReactionsSome(ArrayList<TlObject> reactions) {
        this.reactions = reactions;
    }

    public static ChatReactionsSome read(ByteArrayInputStream bytes) throws IOException {
        ArrayList<TlObject> reactions = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		
		return new ChatReactionsSome(reactions);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new VectorPrimitive(this.reactions).write());
		
		return bOut.toByteArray();
    }
}
