//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class Config extends TlObject {

    public static final int ID = -870702050;

    public boolean default_p2p_contacts;
	public boolean preload_featured_stickers;
	public boolean revoke_pm_inbox;
	public boolean blocked_mode;
	public boolean force_try_ipv6;
	public int date;
	public int expires;
	public TlObject test_mode;
	public int this_dc;
	public ArrayList<TlObject> dc_options;
	public String dc_txt_domain_name;
	public int chat_size_max;
	public int megagroup_size_max;
	public int forwarded_count_max;
	public int online_update_period_ms;
	public int offline_blur_timeout_ms;
	public int offline_idle_timeout_ms;
	public int online_cloud_timeout_ms;
	public int notify_cloud_delay_ms;
	public int notify_default_delay_ms;
	public int push_chat_period_ms;
	public int push_chat_limit;
	public int edit_time_limit;
	public int revoke_time_limit;
	public int revoke_pm_time_limit;
	public int rating_e_decay;
	public int stickers_recent_limit;
	public int channels_read_media_period;
	public int tmp_sessions;
	public int call_receive_timeout_ms;
	public int call_ring_timeout_ms;
	public int call_connect_timeout_ms;
	public int call_packet_timeout_ms;
	public String me_url_prefix;
	public String autoupdate_url_prefix;
	public String gif_search_username;
	public String venue_search_username;
	public String img_search_username;
	public String static_maps_provider;
	public int caption_length_max;
	public int message_length_max;
	public int webfile_dc_id;
	public String suggested_lang_code;
	public int lang_pack_version;
	public int base_lang_pack_version;
	public TlObject reactions_default;
	public String autologin_token;

    public Config(boolean default_p2p_contacts, boolean preload_featured_stickers, boolean revoke_pm_inbox, boolean blocked_mode, boolean force_try_ipv6, int date, int expires, TlObject test_mode, int this_dc, ArrayList<TlObject> dc_options, String dc_txt_domain_name, int chat_size_max, int megagroup_size_max, int forwarded_count_max, int online_update_period_ms, int offline_blur_timeout_ms, int offline_idle_timeout_ms, int online_cloud_timeout_ms, int notify_cloud_delay_ms, int notify_default_delay_ms, int push_chat_period_ms, int push_chat_limit, int edit_time_limit, int revoke_time_limit, int revoke_pm_time_limit, int rating_e_decay, int stickers_recent_limit, int channels_read_media_period, int tmp_sessions, int call_receive_timeout_ms, int call_ring_timeout_ms, int call_connect_timeout_ms, int call_packet_timeout_ms, String me_url_prefix, String autoupdate_url_prefix, String gif_search_username, String venue_search_username, String img_search_username, String static_maps_provider, int caption_length_max, int message_length_max, int webfile_dc_id, String suggested_lang_code, int lang_pack_version, int base_lang_pack_version, TlObject reactions_default, String autologin_token) {
        this.default_p2p_contacts = default_p2p_contacts;
		this.preload_featured_stickers = preload_featured_stickers;
		this.revoke_pm_inbox = revoke_pm_inbox;
		this.blocked_mode = blocked_mode;
		this.force_try_ipv6 = force_try_ipv6;
		this.date = date;
		this.expires = expires;
		this.test_mode = test_mode;
		this.this_dc = this_dc;
		this.dc_options = dc_options;
		this.dc_txt_domain_name = dc_txt_domain_name;
		this.chat_size_max = chat_size_max;
		this.megagroup_size_max = megagroup_size_max;
		this.forwarded_count_max = forwarded_count_max;
		this.online_update_period_ms = online_update_period_ms;
		this.offline_blur_timeout_ms = offline_blur_timeout_ms;
		this.offline_idle_timeout_ms = offline_idle_timeout_ms;
		this.online_cloud_timeout_ms = online_cloud_timeout_ms;
		this.notify_cloud_delay_ms = notify_cloud_delay_ms;
		this.notify_default_delay_ms = notify_default_delay_ms;
		this.push_chat_period_ms = push_chat_period_ms;
		this.push_chat_limit = push_chat_limit;
		this.edit_time_limit = edit_time_limit;
		this.revoke_time_limit = revoke_time_limit;
		this.revoke_pm_time_limit = revoke_pm_time_limit;
		this.rating_e_decay = rating_e_decay;
		this.stickers_recent_limit = stickers_recent_limit;
		this.channels_read_media_period = channels_read_media_period;
		this.tmp_sessions = tmp_sessions;
		this.call_receive_timeout_ms = call_receive_timeout_ms;
		this.call_ring_timeout_ms = call_ring_timeout_ms;
		this.call_connect_timeout_ms = call_connect_timeout_ms;
		this.call_packet_timeout_ms = call_packet_timeout_ms;
		this.me_url_prefix = me_url_prefix;
		this.autoupdate_url_prefix = autoupdate_url_prefix;
		this.gif_search_username = gif_search_username;
		this.venue_search_username = venue_search_username;
		this.img_search_username = img_search_username;
		this.static_maps_provider = static_maps_provider;
		this.caption_length_max = caption_length_max;
		this.message_length_max = message_length_max;
		this.webfile_dc_id = webfile_dc_id;
		this.suggested_lang_code = suggested_lang_code;
		this.lang_pack_version = lang_pack_version;
		this.base_lang_pack_version = base_lang_pack_version;
		this.reactions_default = reactions_default;
		this.autologin_token = autologin_token;
    }

    public static Config read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean default_p2p_contacts = (flags & (1 << 3)) != 0;
		boolean preload_featured_stickers = (flags & (1 << 4)) != 0;
		boolean revoke_pm_inbox = (flags & (1 << 6)) != 0;
		boolean blocked_mode = (flags & (1 << 8)) != 0;
		boolean force_try_ipv6 = (flags & (1 << 14)) != 0;
		int date = IntPrimitive.read(bytes).getValue();
		int expires = IntPrimitive.read(bytes).getValue();
		TlObject test_mode = TlObject.read(bytes);
		int this_dc = IntPrimitive.read(bytes).getValue();
		ArrayList<TlObject> dc_options = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		String dc_txt_domain_name = StringPrimitive.read(bytes).getValue();
		int chat_size_max = IntPrimitive.read(bytes).getValue();
		int megagroup_size_max = IntPrimitive.read(bytes).getValue();
		int forwarded_count_max = IntPrimitive.read(bytes).getValue();
		int online_update_period_ms = IntPrimitive.read(bytes).getValue();
		int offline_blur_timeout_ms = IntPrimitive.read(bytes).getValue();
		int offline_idle_timeout_ms = IntPrimitive.read(bytes).getValue();
		int online_cloud_timeout_ms = IntPrimitive.read(bytes).getValue();
		int notify_cloud_delay_ms = IntPrimitive.read(bytes).getValue();
		int notify_default_delay_ms = IntPrimitive.read(bytes).getValue();
		int push_chat_period_ms = IntPrimitive.read(bytes).getValue();
		int push_chat_limit = IntPrimitive.read(bytes).getValue();
		int edit_time_limit = IntPrimitive.read(bytes).getValue();
		int revoke_time_limit = IntPrimitive.read(bytes).getValue();
		int revoke_pm_time_limit = IntPrimitive.read(bytes).getValue();
		int rating_e_decay = IntPrimitive.read(bytes).getValue();
		int stickers_recent_limit = IntPrimitive.read(bytes).getValue();
		int channels_read_media_period = IntPrimitive.read(bytes).getValue();
		int tmp_sessions = (flags & (1 << 0)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		int call_receive_timeout_ms = IntPrimitive.read(bytes).getValue();
		int call_ring_timeout_ms = IntPrimitive.read(bytes).getValue();
		int call_connect_timeout_ms = IntPrimitive.read(bytes).getValue();
		int call_packet_timeout_ms = IntPrimitive.read(bytes).getValue();
		String me_url_prefix = StringPrimitive.read(bytes).getValue();
		String autoupdate_url_prefix = (flags & (1 << 7)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		String gif_search_username = (flags & (1 << 9)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		String venue_search_username = (flags & (1 << 10)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		String img_search_username = (flags & (1 << 11)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		String static_maps_provider = (flags & (1 << 12)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		int caption_length_max = IntPrimitive.read(bytes).getValue();
		int message_length_max = IntPrimitive.read(bytes).getValue();
		int webfile_dc_id = IntPrimitive.read(bytes).getValue();
		String suggested_lang_code = (flags & (1 << 2)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		int lang_pack_version = (flags & (1 << 2)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		int base_lang_pack_version = (flags & (1 << 2)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		TlObject reactions_default = (flags & (1 << 15)) != 0 ?  TlObject.read(bytes) : null;
		String autologin_token = (flags & (1 << 16)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		
		return new Config(default_p2p_contacts, preload_featured_stickers, revoke_pm_inbox, blocked_mode, force_try_ipv6, date, expires, test_mode, this_dc, dc_options, dc_txt_domain_name, chat_size_max, megagroup_size_max, forwarded_count_max, online_update_period_ms, offline_blur_timeout_ms, offline_idle_timeout_ms, online_cloud_timeout_ms, notify_cloud_delay_ms, notify_default_delay_ms, push_chat_period_ms, push_chat_limit, edit_time_limit, revoke_time_limit, revoke_pm_time_limit, rating_e_decay, stickers_recent_limit, channels_read_media_period, tmp_sessions, call_receive_timeout_ms, call_ring_timeout_ms, call_connect_timeout_ms, call_packet_timeout_ms, me_url_prefix, autoupdate_url_prefix, gif_search_username, venue_search_username, img_search_username, static_maps_provider, caption_length_max, message_length_max, webfile_dc_id, suggested_lang_code, lang_pack_version, base_lang_pack_version, reactions_default, autologin_token);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.default_p2p_contacts ? (1 << 3) : 0;
		flags |= this.preload_featured_stickers ? (1 << 4) : 0;
		flags |= this.revoke_pm_inbox ? (1 << 6) : 0;
		flags |= this.blocked_mode ? (1 << 8) : 0;
		flags |= this.force_try_ipv6 ? (1 << 14) : 0;
		flags |= (this.tmp_sessions != 0) ? (1 << 0) : 0;
		flags |= (this.autoupdate_url_prefix != null) ? (1 << 7) : 0;
		flags |= (this.gif_search_username != null) ? (1 << 9) : 0;
		flags |= (this.venue_search_username != null) ? (1 << 10) : 0;
		flags |= (this.img_search_username != null) ? (1 << 11) : 0;
		flags |= (this.static_maps_provider != null) ? (1 << 12) : 0;
		flags |= (this.suggested_lang_code != null) ? (1 << 2) : 0;
		flags |= (this.lang_pack_version != 0) ? (1 << 2) : 0;
		flags |= (this.base_lang_pack_version != 0) ? (1 << 2) : 0;
		flags |= (this.reactions_default != null) ? (1 << 15) : 0;
		flags |= (this.autologin_token != null) ? (1 << 16) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new IntPrimitive(this.date).write());
		bOut.write(new IntPrimitive(this.expires).write());
		bOut.write(this.test_mode.write());
		bOut.write(new IntPrimitive(this.this_dc).write());
		bOut.write(new VectorPrimitive(this.dc_options).write());
		bOut.write(new StringPrimitive(this.dc_txt_domain_name).write());
		bOut.write(new IntPrimitive(this.chat_size_max).write());
		bOut.write(new IntPrimitive(this.megagroup_size_max).write());
		bOut.write(new IntPrimitive(this.forwarded_count_max).write());
		bOut.write(new IntPrimitive(this.online_update_period_ms).write());
		bOut.write(new IntPrimitive(this.offline_blur_timeout_ms).write());
		bOut.write(new IntPrimitive(this.offline_idle_timeout_ms).write());
		bOut.write(new IntPrimitive(this.online_cloud_timeout_ms).write());
		bOut.write(new IntPrimitive(this.notify_cloud_delay_ms).write());
		bOut.write(new IntPrimitive(this.notify_default_delay_ms).write());
		bOut.write(new IntPrimitive(this.push_chat_period_ms).write());
		bOut.write(new IntPrimitive(this.push_chat_limit).write());
		bOut.write(new IntPrimitive(this.edit_time_limit).write());
		bOut.write(new IntPrimitive(this.revoke_time_limit).write());
		bOut.write(new IntPrimitive(this.revoke_pm_time_limit).write());
		bOut.write(new IntPrimitive(this.rating_e_decay).write());
		bOut.write(new IntPrimitive(this.stickers_recent_limit).write());
		bOut.write(new IntPrimitive(this.channels_read_media_period).write());
		if(this.tmp_sessions != 0)
			bOut.write(new IntPrimitive(this.tmp_sessions).write());
		bOut.write(new IntPrimitive(this.call_receive_timeout_ms).write());
		bOut.write(new IntPrimitive(this.call_ring_timeout_ms).write());
		bOut.write(new IntPrimitive(this.call_connect_timeout_ms).write());
		bOut.write(new IntPrimitive(this.call_packet_timeout_ms).write());
		bOut.write(new StringPrimitive(this.me_url_prefix).write());
		if(this.autoupdate_url_prefix != null)
			bOut.write(new StringPrimitive(this.autoupdate_url_prefix).write());
		if(this.gif_search_username != null)
			bOut.write(new StringPrimitive(this.gif_search_username).write());
		if(this.venue_search_username != null)
			bOut.write(new StringPrimitive(this.venue_search_username).write());
		if(this.img_search_username != null)
			bOut.write(new StringPrimitive(this.img_search_username).write());
		if(this.static_maps_provider != null)
			bOut.write(new StringPrimitive(this.static_maps_provider).write());
		bOut.write(new IntPrimitive(this.caption_length_max).write());
		bOut.write(new IntPrimitive(this.message_length_max).write());
		bOut.write(new IntPrimitive(this.webfile_dc_id).write());
		if(this.suggested_lang_code != null)
			bOut.write(new StringPrimitive(this.suggested_lang_code).write());
		if(this.lang_pack_version != 0)
			bOut.write(new IntPrimitive(this.lang_pack_version).write());
		if(this.base_lang_pack_version != 0)
			bOut.write(new IntPrimitive(this.base_lang_pack_version).write());
		if(this.reactions_default != null)
			bOut.write(this.reactions_default.write());
		if(this.autologin_token != null)
			bOut.write(new StringPrimitive(this.autologin_token).write());
		
		return bOut.toByteArray();
    }
}
