//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class Contact extends TlObject {

    public static final int ID = 341499403;

    public long user_id;
	public TlObject mutual;

    public Contact(long user_id, TlObject mutual) {
        this.user_id = user_id;
		this.mutual = mutual;
    }

    public static Contact read(ByteArrayInputStream bytes) throws IOException {
        long user_id = LongPrimitive.read(bytes).getValue();
		TlObject mutual = TlObject.read(bytes);
		
		return new Contact(user_id, mutual);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new LongPrimitive(this.user_id).write());
		bOut.write(this.mutual.write());
		
		return bOut.toByteArray();
    }
}
