//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.contacts;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ContactsNotModified extends TlObject {

    public static final int ID = -1219778094;

    

    public ContactsNotModified() {
        
    }

    public static ContactsNotModified read(ByteArrayInputStream bytes) throws IOException {
        
		return new ContactsNotModified();
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		
		return bOut.toByteArray();
    }
}
