//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.help;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class DeepLinkInfo extends TlObject {

    public static final int ID = 1783556146;

    public boolean update_app;
	public String message;
	public ArrayList<TlObject> entities;

    public DeepLinkInfo(boolean update_app, String message, ArrayList<TlObject> entities) {
        this.update_app = update_app;
		this.message = message;
		this.entities = entities;
    }

    public static DeepLinkInfo read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean update_app = (flags & (1 << 0)) != 0;
		String message = StringPrimitive.read(bytes).getValue();
		ArrayList<TlObject> entities = (flags & (1 << 1)) != 0 ?  ((VectorPrimitive)TlObject.read(bytes)).getValue() : null;
		
		return new DeepLinkInfo(update_app, message, entities);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.update_app ? (1 << 0) : 0;
		flags |= (this.entities != null) ? (1 << 1) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new StringPrimitive(this.message).write());
		if(this.entities != null)
			bOut.write(new VectorPrimitive(this.entities).write());
		
		return bOut.toByteArray();
    }
}
