//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class DefaultHistoryTTL extends TlObject {

    public static final int ID = 1135897376;

    public int period;

    public DefaultHistoryTTL(int period) {
        this.period = period;
    }

    public static DefaultHistoryTTL read(ByteArrayInputStream bytes) throws IOException {
        int period = IntPrimitive.read(bytes).getValue();
		
		return new DefaultHistoryTTL(period);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new IntPrimitive(this.period).write());
		
		return bOut.toByteArray();
    }
}
