//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class DhConfigNotModified extends TlObject {

    public static final int ID = -1058912715;

    public byte[] random;

    public DhConfigNotModified(byte[] random) {
        this.random = random;
    }

    public static DhConfigNotModified read(ByteArrayInputStream bytes) throws IOException {
        byte[] random = BytesPrimitive.read(bytes).getValue();
		
		return new DhConfigNotModified(random);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new BytesPrimitive(this.random).write());
		
		return bOut.toByteArray();
    }
}
