//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class DiscussionMessage extends TlObject {

    public static final int ID = -1506535550;

    public ArrayList<TlObject> messages;
	public int max_id;
	public int read_inbox_max_id;
	public int read_outbox_max_id;
	public int unread_count;
	public ArrayList<TlObject> chats;
	public ArrayList<TlObject> users;

    public DiscussionMessage(ArrayList<TlObject> messages, int max_id, int read_inbox_max_id, int read_outbox_max_id, int unread_count, ArrayList<TlObject> chats, ArrayList<TlObject> users) {
        this.messages = messages;
		this.max_id = max_id;
		this.read_inbox_max_id = read_inbox_max_id;
		this.read_outbox_max_id = read_outbox_max_id;
		this.unread_count = unread_count;
		this.chats = chats;
		this.users = users;
    }

    public static DiscussionMessage read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		ArrayList<TlObject> messages = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		int max_id = (flags & (1 << 0)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		int read_inbox_max_id = (flags & (1 << 1)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		int read_outbox_max_id = (flags & (1 << 2)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		int unread_count = IntPrimitive.read(bytes).getValue();
		ArrayList<TlObject> chats = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		ArrayList<TlObject> users = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		
		return new DiscussionMessage(messages, max_id, read_inbox_max_id, read_outbox_max_id, unread_count, chats, users);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= (this.max_id != 0) ? (1 << 0) : 0;
		flags |= (this.read_inbox_max_id != 0) ? (1 << 1) : 0;
		flags |= (this.read_outbox_max_id != 0) ? (1 << 2) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new VectorPrimitive(this.messages).write());
		if(this.max_id != 0)
			bOut.write(new IntPrimitive(this.max_id).write());
		if(this.read_inbox_max_id != 0)
			bOut.write(new IntPrimitive(this.read_inbox_max_id).write());
		if(this.read_outbox_max_id != 0)
			bOut.write(new IntPrimitive(this.read_outbox_max_id).write());
		bOut.write(new IntPrimitive(this.unread_count).write());
		bOut.write(new VectorPrimitive(this.chats).write());
		bOut.write(new VectorPrimitive(this.users).write());
		
		return bOut.toByteArray();
    }
}
