//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class DocumentAttributeSticker extends TlObject {

    public static final int ID = 1662637586;

    public boolean mask;
	public String alt;
	public TlObject stickerset;
	public TlObject mask_coords;

    public DocumentAttributeSticker(boolean mask, String alt, TlObject stickerset, TlObject mask_coords) {
        this.mask = mask;
		this.alt = alt;
		this.stickerset = stickerset;
		this.mask_coords = mask_coords;
    }

    public static DocumentAttributeSticker read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean mask = (flags & (1 << 1)) != 0;
		String alt = StringPrimitive.read(bytes).getValue();
		TlObject stickerset = TlObject.read(bytes);
		TlObject mask_coords = (flags & (1 << 0)) != 0 ?  TlObject.read(bytes) : null;
		
		return new DocumentAttributeSticker(mask, alt, stickerset, mask_coords);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.mask ? (1 << 1) : 0;
		flags |= (this.mask_coords != null) ? (1 << 0) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new StringPrimitive(this.alt).write());
		bOut.write(this.stickerset.write());
		if(this.mask_coords != null)
			bOut.write(this.mask_coords.write());
		
		return bOut.toByteArray();
    }
}
