//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.account;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class EmojiStatuses extends TlObject {

    public static final int ID = -1866176559;

    public long hash;
	public ArrayList<TlObject> statuses;

    public EmojiStatuses(long hash, ArrayList<TlObject> statuses) {
        this.hash = hash;
		this.statuses = statuses;
    }

    public static EmojiStatuses read(ByteArrayInputStream bytes) throws IOException {
        long hash = LongPrimitive.read(bytes).getValue();
		ArrayList<TlObject> statuses = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		
		return new EmojiStatuses(hash, statuses);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new LongPrimitive(this.hash).write());
		bOut.write(new VectorPrimitive(this.statuses).write());
		
		return bOut.toByteArray();
    }
}
