//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class EncryptedChatWaiting extends TlObject {

    public static final int ID = 1722964307;

    public int id;
	public long access_hash;
	public int date;
	public long admin_id;
	public long participant_id;

    public EncryptedChatWaiting(int id, long access_hash, int date, long admin_id, long participant_id) {
        this.id = id;
		this.access_hash = access_hash;
		this.date = date;
		this.admin_id = admin_id;
		this.participant_id = participant_id;
    }

    public static EncryptedChatWaiting read(ByteArrayInputStream bytes) throws IOException {
        int id = IntPrimitive.read(bytes).getValue();
		long access_hash = LongPrimitive.read(bytes).getValue();
		int date = IntPrimitive.read(bytes).getValue();
		long admin_id = LongPrimitive.read(bytes).getValue();
		long participant_id = LongPrimitive.read(bytes).getValue();
		
		return new EncryptedChatWaiting(id, access_hash, date, admin_id, participant_id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new IntPrimitive(this.id).write());
		bOut.write(new LongPrimitive(this.access_hash).write());
		bOut.write(new IntPrimitive(this.date).write());
		bOut.write(new LongPrimitive(this.admin_id).write());
		bOut.write(new LongPrimitive(this.participant_id).write());
		
		return bOut.toByteArray();
    }
}
