//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class EncryptedMessage extends TlObject {

    public static final int ID = -317144808;

    public long random_id;
	public int chat_id;
	public int date;
	public byte[] bytesv;
	public TlObject file;

    public EncryptedMessage(long random_id, int chat_id, int date, byte[] bytesv, TlObject file) {
        this.random_id = random_id;
		this.chat_id = chat_id;
		this.date = date;
		this.bytesv = bytesv;
		this.file = file;
    }

    public static EncryptedMessage read(ByteArrayInputStream bytes) throws IOException {
        long random_id = LongPrimitive.read(bytes).getValue();
		int chat_id = IntPrimitive.read(bytes).getValue();
		int date = IntPrimitive.read(bytes).getValue();
		byte[] bytesv = BytesPrimitive.read(bytes).getValue();
		TlObject file = TlObject.read(bytes);
		
		return new EncryptedMessage(random_id, chat_id, date, bytesv, file);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new LongPrimitive(this.random_id).write());
		bOut.write(new IntPrimitive(this.chat_id).write());
		bOut.write(new IntPrimitive(this.date).write());
		bOut.write(new BytesPrimitive(this.bytesv).write());
		bOut.write(this.file.write());
		
		return bOut.toByteArray();
    }
}
