//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.phone;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ExportedGroupCallInvite extends TlObject {

    public static final int ID = 541839704;

    public String link;

    public ExportedGroupCallInvite(String link) {
        this.link = link;
    }

    public static ExportedGroupCallInvite read(ByteArrayInputStream bytes) throws IOException {
        String link = StringPrimitive.read(bytes).getValue();
		
		return new ExportedGroupCallInvite(link);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new StringPrimitive(this.link).write());
		
		return bOut.toByteArray();
    }
}
