//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.chatlists;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ExportedChatlistInvite extends TlObject {

    public static final int ID = 283567014;

    public TlObject filter;
	public TlObject invite;

    public ExportedChatlistInvite(TlObject filter, TlObject invite) {
        this.filter = filter;
		this.invite = invite;
    }

    public static ExportedChatlistInvite read(ByteArrayInputStream bytes) throws IOException {
        TlObject filter = TlObject.read(bytes);
		TlObject invite = TlObject.read(bytes);
		
		return new ExportedChatlistInvite(filter, invite);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.filter.write());
		bOut.write(this.invite.write());
		
		return bOut.toByteArray();
    }
}
