//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.upload;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class File extends TlObject {

    public static final int ID = 157948117;

    public TlObject type;
	public int mtime;
	public byte[] bytesv;

    public File(TlObject type, int mtime, byte[] bytesv) {
        this.type = type;
		this.mtime = mtime;
		this.bytesv = bytesv;
    }

    public static File read(ByteArrayInputStream bytes) throws IOException {
        TlObject type = TlObject.read(bytes);
		int mtime = IntPrimitive.read(bytes).getValue();
		byte[] bytesv = BytesPrimitive.read(bytes).getValue();
		
		return new File(type, mtime, bytesv);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.type.write());
		bOut.write(new IntPrimitive(this.mtime).write());
		bOut.write(new BytesPrimitive(this.bytesv).write());
		
		return bOut.toByteArray();
    }
}
