//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class GlobalPrivacySettings extends TlObject {

    public static final int ID = -1096616924;

    public TlObject archive_and_mute_new_noncontact_peers;

    public GlobalPrivacySettings(TlObject archive_and_mute_new_noncontact_peers) {
        this.archive_and_mute_new_noncontact_peers = archive_and_mute_new_noncontact_peers;
    }

    public static GlobalPrivacySettings read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		TlObject archive_and_mute_new_noncontact_peers = (flags & (1 << 0)) != 0 ?  TlObject.read(bytes) : null;
		
		return new GlobalPrivacySettings(archive_and_mute_new_noncontact_peers);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= (this.archive_and_mute_new_noncontact_peers != null) ? (1 << 0) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		if(this.archive_and_mute_new_noncontact_peers != null)
			bOut.write(this.archive_and_mute_new_noncontact_peers.write());
		
		return bOut.toByteArray();
    }
}
