//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.phone;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class GroupCallStreamRtmpUrl extends TlObject {

    public static final int ID = 767505458;

    public String url;
	public String key;

    public GroupCallStreamRtmpUrl(String url, String key) {
        this.url = url;
		this.key = key;
    }

    public static GroupCallStreamRtmpUrl read(ByteArrayInputStream bytes) throws IOException {
        String url = StringPrimitive.read(bytes).getValue();
		String key = StringPrimitive.read(bytes).getValue();
		
		return new GroupCallStreamRtmpUrl(url, key);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new StringPrimitive(this.url).write());
		bOut.write(new StringPrimitive(this.key).write());
		
		return bOut.toByteArray();
    }
}
