//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class InlineBotSwitchPM extends TlObject {

    public static final int ID = 1008755359;

    public String text;
	public String start_param;

    public InlineBotSwitchPM(String text, String start_param) {
        this.text = text;
		this.start_param = start_param;
    }

    public static InlineBotSwitchPM read(ByteArrayInputStream bytes) throws IOException {
        String text = StringPrimitive.read(bytes).getValue();
		String start_param = StringPrimitive.read(bytes).getValue();
		
		return new InlineBotSwitchPM(text, start_param);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new StringPrimitive(this.text).write());
		bOut.write(new StringPrimitive(this.start_param).write());
		
		return bOut.toByteArray();
    }
}
