//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class InputMediaVenue extends TlObject {

    public static final int ID = -1052959727;

    public TlObject geo_point;
	public String title;
	public String address;
	public String provider;
	public String venue_id;
	public String venue_type;

    public InputMediaVenue(TlObject geo_point, String title, String address, String provider, String venue_id, String venue_type) {
        this.geo_point = geo_point;
		this.title = title;
		this.address = address;
		this.provider = provider;
		this.venue_id = venue_id;
		this.venue_type = venue_type;
    }

    public static InputMediaVenue read(ByteArrayInputStream bytes) throws IOException {
        TlObject geo_point = TlObject.read(bytes);
		String title = StringPrimitive.read(bytes).getValue();
		String address = StringPrimitive.read(bytes).getValue();
		String provider = StringPrimitive.read(bytes).getValue();
		String venue_id = StringPrimitive.read(bytes).getValue();
		String venue_type = StringPrimitive.read(bytes).getValue();
		
		return new InputMediaVenue(geo_point, title, address, provider, venue_id, venue_type);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.geo_point.write());
		bOut.write(new StringPrimitive(this.title).write());
		bOut.write(new StringPrimitive(this.address).write());
		bOut.write(new StringPrimitive(this.provider).write());
		bOut.write(new StringPrimitive(this.venue_id).write());
		bOut.write(new StringPrimitive(this.venue_type).write());
		
		return bOut.toByteArray();
    }
}
