//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class InputMediaDocument extends TlObject {

    public static final int ID = 860303448;

    public boolean spoiler;
	public TlObject id;
	public int ttl_seconds;
	public String query;

    public InputMediaDocument(boolean spoiler, TlObject id, int ttl_seconds, String query) {
        this.spoiler = spoiler;
		this.id = id;
		this.ttl_seconds = ttl_seconds;
		this.query = query;
    }

    public static InputMediaDocument read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean spoiler = (flags & (1 << 2)) != 0;
		TlObject id = TlObject.read(bytes);
		int ttl_seconds = (flags & (1 << 0)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		String query = (flags & (1 << 1)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		
		return new InputMediaDocument(spoiler, id, ttl_seconds, query);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.spoiler ? (1 << 2) : 0;
		flags |= (this.ttl_seconds != 0) ? (1 << 0) : 0;
		flags |= (this.query != null) ? (1 << 1) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(this.id.write());
		if(this.ttl_seconds != 0)
			bOut.write(new IntPrimitive(this.ttl_seconds).write());
		if(this.query != null)
			bOut.write(new StringPrimitive(this.query).write());
		
		return bOut.toByteArray();
    }
}
