//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class InputBotInlineMessageGame extends TlObject {

    public static final int ID = 1262639204;

    public TlObject reply_markup;

    public InputBotInlineMessageGame(TlObject reply_markup) {
        this.reply_markup = reply_markup;
    }

    public static InputBotInlineMessageGame read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		TlObject reply_markup = (flags & (1 << 2)) != 0 ?  TlObject.read(bytes) : null;
		
		return new InputBotInlineMessageGame(reply_markup);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= (this.reply_markup != null) ? (1 << 2) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		if(this.reply_markup != null)
			bOut.write(this.reply_markup.write());
		
		return bOut.toByteArray();
    }
}
