//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class InputMediaPoll extends TlObject {

    public static final int ID = 261416433;

    public TlObject poll;
	public ArrayList<TlObject> correct_answers;
	public String solution;
	public ArrayList<TlObject> solution_entities;

    public InputMediaPoll(TlObject poll, ArrayList<TlObject> correct_answers, String solution, ArrayList<TlObject> solution_entities) {
        this.poll = poll;
		this.correct_answers = correct_answers;
		this.solution = solution;
		this.solution_entities = solution_entities;
    }

    public static InputMediaPoll read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		TlObject poll = TlObject.read(bytes);
		ArrayList<TlObject> correct_answers = (flags & (1 << 0)) != 0 ?  ((VectorPrimitive)TlObject.read(bytes)).getValue() : null;
		String solution = (flags & (1 << 1)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		ArrayList<TlObject> solution_entities = (flags & (1 << 1)) != 0 ?  ((VectorPrimitive)TlObject.read(bytes)).getValue() : null;
		
		return new InputMediaPoll(poll, correct_answers, solution, solution_entities);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= (this.correct_answers != null) ? (1 << 0) : 0;
		flags |= (this.solution != null) ? (1 << 1) : 0;
		flags |= (this.solution_entities != null) ? (1 << 1) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(this.poll.write());
		if(this.correct_answers != null)
			bOut.write(new VectorPrimitive(this.correct_answers).write());
		if(this.solution != null)
			bOut.write(new StringPrimitive(this.solution).write());
		if(this.solution_entities != null)
			bOut.write(new VectorPrimitive(this.solution_entities).write());
		
		return bOut.toByteArray();
    }
}
