//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class InputGameShortName extends TlObject {

    public static final int ID = -1020139510;

    public TlObject bot_id;
	public String short_name;

    public InputGameShortName(TlObject bot_id, String short_name) {
        this.bot_id = bot_id;
		this.short_name = short_name;
    }

    public static InputGameShortName read(ByteArrayInputStream bytes) throws IOException {
        TlObject bot_id = TlObject.read(bytes);
		String short_name = StringPrimitive.read(bytes).getValue();
		
		return new InputGameShortName(bot_id, short_name);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.bot_id.write());
		bOut.write(new StringPrimitive(this.short_name).write());
		
		return bOut.toByteArray();
    }
}
