//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class InputSecureFileUploaded extends TlObject {

    public static final int ID = 859091184;

    public long id;
	public int parts;
	public String md5_checksum;
	public byte[] file_hash;
	public byte[] secret;

    public InputSecureFileUploaded(long id, int parts, String md5_checksum, byte[] file_hash, byte[] secret) {
        this.id = id;
		this.parts = parts;
		this.md5_checksum = md5_checksum;
		this.file_hash = file_hash;
		this.secret = secret;
    }

    public static InputSecureFileUploaded read(ByteArrayInputStream bytes) throws IOException {
        long id = LongPrimitive.read(bytes).getValue();
		int parts = IntPrimitive.read(bytes).getValue();
		String md5_checksum = StringPrimitive.read(bytes).getValue();
		byte[] file_hash = BytesPrimitive.read(bytes).getValue();
		byte[] secret = BytesPrimitive.read(bytes).getValue();
		
		return new InputSecureFileUploaded(id, parts, md5_checksum, file_hash, secret);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new LongPrimitive(this.id).write());
		bOut.write(new IntPrimitive(this.parts).write());
		bOut.write(new StringPrimitive(this.md5_checksum).write());
		bOut.write(new BytesPrimitive(this.file_hash).write());
		bOut.write(new BytesPrimitive(this.secret).write());
		
		return bOut.toByteArray();
    }
}
