//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class InputStorePaymentGiftPremium extends TlObject {

    public static final int ID = 1634697192;

    public TlObject user_id;
	public String currency;
	public long amount;

    public InputStorePaymentGiftPremium(TlObject user_id, String currency, long amount) {
        this.user_id = user_id;
		this.currency = currency;
		this.amount = amount;
    }

    public static InputStorePaymentGiftPremium read(ByteArrayInputStream bytes) throws IOException {
        TlObject user_id = TlObject.read(bytes);
		String currency = StringPrimitive.read(bytes).getValue();
		long amount = LongPrimitive.read(bytes).getValue();
		
		return new InputStorePaymentGiftPremium(user_id, currency, amount);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.user_id.write());
		bOut.write(new StringPrimitive(this.currency).write());
		bOut.write(new LongPrimitive(this.amount).write());
		
		return bOut.toByteArray();
    }
}
