//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class InputKeyboardButtonUserProfile extends TlObject {

    public static final int ID = -376962181;

    public String text;
	public TlObject user_id;

    public InputKeyboardButtonUserProfile(String text, TlObject user_id) {
        this.text = text;
		this.user_id = user_id;
    }

    public static InputKeyboardButtonUserProfile read(ByteArrayInputStream bytes) throws IOException {
        String text = StringPrimitive.read(bytes).getValue();
		TlObject user_id = TlObject.read(bytes);
		
		return new InputKeyboardButtonUserProfile(text, user_id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new StringPrimitive(this.text).write());
		bOut.write(this.user_id.write());
		
		return bOut.toByteArray();
    }
}
