//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class JsonNumber extends TlObject {

    public static final int ID = 736157604;

    public TlObject value;

    public JsonNumber(TlObject value) {
        this.value = value;
    }

    public static JsonNumber read(ByteArrayInputStream bytes) throws IOException {
        TlObject value = TlObject.read(bytes);
		
		return new JsonNumber(value);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.value.write());
		
		return bOut.toByteArray();
    }
}
