//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class LangPackStringDeleted extends TlObject {

    public static final int ID = 695856818;

    public String key;

    public LangPackStringDeleted(String key) {
        this.key = key;
    }

    public static LangPackStringDeleted read(ByteArrayInputStream bytes) throws IOException {
        String key = StringPrimitive.read(bytes).getValue();
		
		return new LangPackStringDeleted(key);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new StringPrimitive(this.key).write());
		
		return bOut.toByteArray();
    }
}
