//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.auth;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class LoginToken extends TlObject {

    public static final int ID = 1654593920;

    public int expires;
	public byte[] token;

    public LoginToken(int expires, byte[] token) {
        this.expires = expires;
		this.token = token;
    }

    public static LoginToken read(ByteArrayInputStream bytes) throws IOException {
        int expires = IntPrimitive.read(bytes).getValue();
		byte[] token = BytesPrimitive.read(bytes).getValue();
		
		return new LoginToken(expires, token);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new IntPrimitive(this.expires).write());
		bOut.write(new BytesPrimitive(this.token).write());
		
		return bOut.toByteArray();
    }
}
