//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.auth;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class LoginTokenSuccess extends TlObject {

    public static final int ID = 957176926;

    public TlObject authorization;

    public LoginTokenSuccess(TlObject authorization) {
        this.authorization = authorization;
    }

    public static LoginTokenSuccess read(ByteArrayInputStream bytes) throws IOException {
        TlObject authorization = TlObject.read(bytes);
		
		return new LoginTokenSuccess(authorization);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.authorization.write());
		
		return bOut.toByteArray();
    }
}
