//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.auth;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class LoginTokenMigrateTo extends TlObject {

    public static final int ID = 110008598;

    public int dc_id;
	public byte[] token;

    public LoginTokenMigrateTo(int dc_id, byte[] token) {
        this.dc_id = dc_id;
		this.token = token;
    }

    public static LoginTokenMigrateTo read(ByteArrayInputStream bytes) throws IOException {
        int dc_id = IntPrimitive.read(bytes).getValue();
		byte[] token = BytesPrimitive.read(bytes).getValue();
		
		return new LoginTokenMigrateTo(dc_id, token);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new IntPrimitive(this.dc_id).write());
		bOut.write(new BytesPrimitive(this.token).write());
		
		return bOut.toByteArray();
    }
}
