//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class MessageEmpty extends TlObject {

    public static final int ID = -1868117372;

    public int id;
	public TlObject peer_id;

    public MessageEmpty(int id, TlObject peer_id) {
        this.id = id;
		this.peer_id = peer_id;
    }

    public static MessageEmpty read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		int id = IntPrimitive.read(bytes).getValue();
		TlObject peer_id = (flags & (1 << 0)) != 0 ?  TlObject.read(bytes) : null;
		
		return new MessageEmpty(id, peer_id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= (this.peer_id != null) ? (1 << 0) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new IntPrimitive(this.id).write());
		if(this.peer_id != null)
			bOut.write(this.peer_id.write());
		
		return bOut.toByteArray();
    }
}
