//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class MessageReplies extends TlObject {

    public static final int ID = -2083123262;

    public boolean comments;
	public int replies;
	public int replies_pts;
	public ArrayList<TlObject> recent_repliers;
	public long channel_id;
	public int max_id;
	public int read_max_id;

    public MessageReplies(boolean comments, int replies, int replies_pts, ArrayList<TlObject> recent_repliers, long channel_id, int max_id, int read_max_id) {
        this.comments = comments;
		this.replies = replies;
		this.replies_pts = replies_pts;
		this.recent_repliers = recent_repliers;
		this.channel_id = channel_id;
		this.max_id = max_id;
		this.read_max_id = read_max_id;
    }

    public static MessageReplies read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean comments = (flags & (1 << 0)) != 0;
		int replies = IntPrimitive.read(bytes).getValue();
		int replies_pts = IntPrimitive.read(bytes).getValue();
		ArrayList<TlObject> recent_repliers = (flags & (1 << 1)) != 0 ?  ((VectorPrimitive)TlObject.read(bytes)).getValue() : null;
		long channel_id = (flags & (1 << 0)) != 0 ?  LongPrimitive.read(bytes).getValue() : 0;
		int max_id = (flags & (1 << 2)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		int read_max_id = (flags & (1 << 3)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		
		return new MessageReplies(comments, replies, replies_pts, recent_repliers, channel_id, max_id, read_max_id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.comments ? (1 << 0) : 0;
		flags |= (this.recent_repliers != null) ? (1 << 1) : 0;
		flags |= (this.channel_id != 0) ? (1 << 0) : 0;
		flags |= (this.max_id != 0) ? (1 << 2) : 0;
		flags |= (this.read_max_id != 0) ? (1 << 3) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new IntPrimitive(this.replies).write());
		bOut.write(new IntPrimitive(this.replies_pts).write());
		if(this.recent_repliers != null)
			bOut.write(new VectorPrimitive(this.recent_repliers).write());
		if(this.channel_id != 0)
			bOut.write(new LongPrimitive(this.channel_id).write());
		if(this.max_id != 0)
			bOut.write(new IntPrimitive(this.max_id).write());
		if(this.read_max_id != 0)
			bOut.write(new IntPrimitive(this.read_max_id).write());
		
		return bOut.toByteArray();
    }
}
