//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class MessageReactions extends TlObject {

    public static final int ID = 1328256121;

    public boolean min;
	public boolean can_see_list;
	public ArrayList<TlObject> results;
	public ArrayList<TlObject> recent_reactions;

    public MessageReactions(boolean min, boolean can_see_list, ArrayList<TlObject> results, ArrayList<TlObject> recent_reactions) {
        this.min = min;
		this.can_see_list = can_see_list;
		this.results = results;
		this.recent_reactions = recent_reactions;
    }

    public static MessageReactions read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean min = (flags & (1 << 0)) != 0;
		boolean can_see_list = (flags & (1 << 2)) != 0;
		ArrayList<TlObject> results = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		ArrayList<TlObject> recent_reactions = (flags & (1 << 1)) != 0 ?  ((VectorPrimitive)TlObject.read(bytes)).getValue() : null;
		
		return new MessageReactions(min, can_see_list, results, recent_reactions);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.min ? (1 << 0) : 0;
		flags |= this.can_see_list ? (1 << 2) : 0;
		flags |= (this.recent_reactions != null) ? (1 << 1) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new VectorPrimitive(this.results).write());
		if(this.recent_reactions != null)
			bOut.write(new VectorPrimitive(this.recent_reactions).write());
		
		return bOut.toByteArray();
    }
}
