//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class MessageMediaGame extends TlObject {

    public static final int ID = -38694904;

    public TlObject game;

    public MessageMediaGame(TlObject game) {
        this.game = game;
    }

    public static MessageMediaGame read(ByteArrayInputStream bytes) throws IOException {
        TlObject game = TlObject.read(bytes);
		
		return new MessageMediaGame(game);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.game.write());
		
		return bOut.toByteArray();
    }
}
