//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class MessageMediaPoll extends TlObject {

    public static final int ID = 1272375192;

    public TlObject poll;
	public TlObject results;

    public MessageMediaPoll(TlObject poll, TlObject results) {
        this.poll = poll;
		this.results = results;
    }

    public static MessageMediaPoll read(ByteArrayInputStream bytes) throws IOException {
        TlObject poll = TlObject.read(bytes);
		TlObject results = TlObject.read(bytes);
		
		return new MessageMediaPoll(poll, results);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.poll.write());
		bOut.write(this.results.write());
		
		return bOut.toByteArray();
    }
}
