//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class MessageExtendedMedia extends TlObject {

    public static final int ID = -297296796;

    public TlObject media;

    public MessageExtendedMedia(TlObject media) {
        this.media = media;
    }

    public static MessageExtendedMedia read(ByteArrayInputStream bytes) throws IOException {
        TlObject media = TlObject.read(bytes);
		
		return new MessageExtendedMedia(media);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.media.write());
		
		return bOut.toByteArray();
    }
}
