//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class MessageActionTopicCreate extends TlObject {

    public static final int ID = 228168278;

    public String title;
	public int icon_color;
	public long icon_emoji_id;

    public MessageActionTopicCreate(String title, int icon_color, long icon_emoji_id) {
        this.title = title;
		this.icon_color = icon_color;
		this.icon_emoji_id = icon_emoji_id;
    }

    public static MessageActionTopicCreate read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		String title = StringPrimitive.read(bytes).getValue();
		int icon_color = IntPrimitive.read(bytes).getValue();
		long icon_emoji_id = (flags & (1 << 0)) != 0 ?  LongPrimitive.read(bytes).getValue() : 0;
		
		return new MessageActionTopicCreate(title, icon_color, icon_emoji_id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= (this.icon_emoji_id != 0) ? (1 << 0) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new StringPrimitive(this.title).write());
		bOut.write(new IntPrimitive(this.icon_color).write());
		if(this.icon_emoji_id != 0)
			bOut.write(new LongPrimitive(this.icon_emoji_id).write());
		
		return bOut.toByteArray();
    }
}
