//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class MessageMediaGeo extends TlObject {

    public static final int ID = 1457575028;

    public TlObject geo;

    public MessageMediaGeo(TlObject geo) {
        this.geo = geo;
    }

    public static MessageMediaGeo read(ByteArrayInputStream bytes) throws IOException {
        TlObject geo = TlObject.read(bytes);
		
		return new MessageMediaGeo(geo);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.geo.write());
		
		return bOut.toByteArray();
    }
}
