//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.stats;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class MessageStats extends TlObject {

    public static final int ID = -1986399595;

    public TlObject views_graph;

    public MessageStats(TlObject views_graph) {
        this.views_graph = views_graph;
    }

    public static MessageStats read(ByteArrayInputStream bytes) throws IOException {
        TlObject views_graph = TlObject.read(bytes);
		
		return new MessageStats(views_graph);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.views_graph.write());
		
		return bOut.toByteArray();
    }
}
