//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class MessagePeerReaction extends TlObject {

    public static final int ID = -1938180548;

    public boolean big;
	public boolean unread;
	public boolean my;
	public TlObject peer_id;
	public int date;
	public TlObject reaction;

    public MessagePeerReaction(boolean big, boolean unread, boolean my, TlObject peer_id, int date, TlObject reaction) {
        this.big = big;
		this.unread = unread;
		this.my = my;
		this.peer_id = peer_id;
		this.date = date;
		this.reaction = reaction;
    }

    public static MessagePeerReaction read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean big = (flags & (1 << 0)) != 0;
		boolean unread = (flags & (1 << 1)) != 0;
		boolean my = (flags & (1 << 2)) != 0;
		TlObject peer_id = TlObject.read(bytes);
		int date = IntPrimitive.read(bytes).getValue();
		TlObject reaction = TlObject.read(bytes);
		
		return new MessagePeerReaction(big, unread, my, peer_id, date, reaction);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.big ? (1 << 0) : 0;
		flags |= this.unread ? (1 << 1) : 0;
		flags |= this.my ? (1 << 2) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(this.peer_id.write());
		bOut.write(new IntPrimitive(this.date).write());
		bOut.write(this.reaction.write());
		
		return bOut.toByteArray();
    }
}
