//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class NearestDc extends TlObject {

    public static final int ID = -1910892683;

    public String country;
	public int this_dc;
	public int nearest_dc;

    public NearestDc(String country, int this_dc, int nearest_dc) {
        this.country = country;
		this.this_dc = this_dc;
		this.nearest_dc = nearest_dc;
    }

    public static NearestDc read(ByteArrayInputStream bytes) throws IOException {
        String country = StringPrimitive.read(bytes).getValue();
		int this_dc = IntPrimitive.read(bytes).getValue();
		int nearest_dc = IntPrimitive.read(bytes).getValue();
		
		return new NearestDc(country, this_dc, nearest_dc);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new StringPrimitive(this.country).write());
		bOut.write(new IntPrimitive(this.this_dc).write());
		bOut.write(new IntPrimitive(this.nearest_dc).write());
		
		return bOut.toByteArray();
    }
}
