//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class NotifyForumTopic extends TlObject {

    public static final int ID = 577659656;

    public TlObject peer;
	public int top_msg_id;

    public NotifyForumTopic(TlObject peer, int top_msg_id) {
        this.peer = peer;
		this.top_msg_id = top_msg_id;
    }

    public static NotifyForumTopic read(ByteArrayInputStream bytes) throws IOException {
        TlObject peer = TlObject.read(bytes);
		int top_msg_id = IntPrimitive.read(bytes).getValue();
		
		return new NotifyForumTopic(peer, top_msg_id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.peer.write());
		bOut.write(new IntPrimitive(this.top_msg_id).write());
		
		return bOut.toByteArray();
    }
}
