//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class PageBlockPreformatted extends TlObject {

    public static final int ID = -1066346178;

    public TlObject text;
	public String language;

    public PageBlockPreformatted(TlObject text, String language) {
        this.text = text;
		this.language = language;
    }

    public static PageBlockPreformatted read(ByteArrayInputStream bytes) throws IOException {
        TlObject text = TlObject.read(bytes);
		String language = StringPrimitive.read(bytes).getValue();
		
		return new PageBlockPreformatted(text, language);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.text.write());
		bOut.write(new StringPrimitive(this.language).write());
		
		return bOut.toByteArray();
    }
}
