//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class PageBlockOrderedList extends TlObject {

    public static final int ID = -1702174239;

    public ArrayList<TlObject> items;

    public PageBlockOrderedList(ArrayList<TlObject> items) {
        this.items = items;
    }

    public static PageBlockOrderedList read(ByteArrayInputStream bytes) throws IOException {
        ArrayList<TlObject> items = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		
		return new PageBlockOrderedList(items);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new VectorPrimitive(this.items).write());
		
		return bOut.toByteArray();
    }
}
