//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class PageBlockAudio extends TlObject {

    public static final int ID = -2143067670;

    public long audio_id;
	public TlObject caption;

    public PageBlockAudio(long audio_id, TlObject caption) {
        this.audio_id = audio_id;
		this.caption = caption;
    }

    public static PageBlockAudio read(ByteArrayInputStream bytes) throws IOException {
        long audio_id = LongPrimitive.read(bytes).getValue();
		TlObject caption = TlObject.read(bytes);
		
		return new PageBlockAudio(audio_id, caption);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new LongPrimitive(this.audio_id).write());
		bOut.write(this.caption.write());
		
		return bOut.toByteArray();
    }
}
