//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.account;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class Password extends TlObject {

    public static final int ID = -1787080453;

    public boolean has_recovery;
	public boolean has_secure_values;
	public boolean has_password;
	public TlObject current_algo;
	public byte[] srp_B;
	public long srp_id;
	public String hint;
	public String email_unconfirmed_pattern;
	public TlObject new_algo;
	public TlObject new_secure_algo;
	public byte[] secure_random;
	public int pending_reset_date;
	public String login_email_pattern;

    public Password(boolean has_recovery, boolean has_secure_values, boolean has_password, TlObject current_algo, byte[] srp_B, long srp_id, String hint, String email_unconfirmed_pattern, TlObject new_algo, TlObject new_secure_algo, byte[] secure_random, int pending_reset_date, String login_email_pattern) {
        this.has_recovery = has_recovery;
		this.has_secure_values = has_secure_values;
		this.has_password = has_password;
		this.current_algo = current_algo;
		this.srp_B = srp_B;
		this.srp_id = srp_id;
		this.hint = hint;
		this.email_unconfirmed_pattern = email_unconfirmed_pattern;
		this.new_algo = new_algo;
		this.new_secure_algo = new_secure_algo;
		this.secure_random = secure_random;
		this.pending_reset_date = pending_reset_date;
		this.login_email_pattern = login_email_pattern;
    }

    public static Password read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean has_recovery = (flags & (1 << 0)) != 0;
		boolean has_secure_values = (flags & (1 << 1)) != 0;
		boolean has_password = (flags & (1 << 2)) != 0;
		TlObject current_algo = (flags & (1 << 2)) != 0 ?  TlObject.read(bytes) : null;
		byte[] srp_B = (flags & (1 << 2)) != 0 ?  BytesPrimitive.read(bytes).getValue() : null;
		long srp_id = (flags & (1 << 2)) != 0 ?  LongPrimitive.read(bytes).getValue() : 0;
		String hint = (flags & (1 << 3)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		String email_unconfirmed_pattern = (flags & (1 << 4)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		TlObject new_algo = TlObject.read(bytes);
		TlObject new_secure_algo = TlObject.read(bytes);
		byte[] secure_random = BytesPrimitive.read(bytes).getValue();
		int pending_reset_date = (flags & (1 << 5)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		String login_email_pattern = (flags & (1 << 6)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		
		return new Password(has_recovery, has_secure_values, has_password, current_algo, srp_B, srp_id, hint, email_unconfirmed_pattern, new_algo, new_secure_algo, secure_random, pending_reset_date, login_email_pattern);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.has_recovery ? (1 << 0) : 0;
		flags |= this.has_secure_values ? (1 << 1) : 0;
		flags |= this.has_password ? (1 << 2) : 0;
		flags |= (this.current_algo != null) ? (1 << 2) : 0;
		flags |= (this.srp_B != null) ? (1 << 2) : 0;
		flags |= (this.srp_id != 0) ? (1 << 2) : 0;
		flags |= (this.hint != null) ? (1 << 3) : 0;
		flags |= (this.email_unconfirmed_pattern != null) ? (1 << 4) : 0;
		flags |= (this.pending_reset_date != 0) ? (1 << 5) : 0;
		flags |= (this.login_email_pattern != null) ? (1 << 6) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		if(this.current_algo != null)
			bOut.write(this.current_algo.write());
		if(this.srp_B != null)
			bOut.write(new BytesPrimitive(this.srp_B).write());
		if(this.srp_id != 0)
			bOut.write(new LongPrimitive(this.srp_id).write());
		if(this.hint != null)
			bOut.write(new StringPrimitive(this.hint).write());
		if(this.email_unconfirmed_pattern != null)
			bOut.write(new StringPrimitive(this.email_unconfirmed_pattern).write());
		bOut.write(this.new_algo.write());
		bOut.write(this.new_secure_algo.write());
		bOut.write(new BytesPrimitive(this.secure_random).write());
		if(this.pending_reset_date != 0)
			bOut.write(new IntPrimitive(this.pending_reset_date).write());
		if(this.login_email_pattern != null)
			bOut.write(new StringPrimitive(this.login_email_pattern).write());
		
		return bOut.toByteArray();
    }
}
