//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class PaymentCharge extends TlObject {

    public static final int ID = -368917890;

    public String id;
	public String provider_charge_id;

    public PaymentCharge(String id, String provider_charge_id) {
        this.id = id;
		this.provider_charge_id = provider_charge_id;
    }

    public static PaymentCharge read(ByteArrayInputStream bytes) throws IOException {
        String id = StringPrimitive.read(bytes).getValue();
		String provider_charge_id = StringPrimitive.read(bytes).getValue();
		
		return new PaymentCharge(id, provider_charge_id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new StringPrimitive(this.id).write());
		bOut.write(new StringPrimitive(this.provider_charge_id).write());
		
		return bOut.toByteArray();
    }
}
