//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class PeerDialogs extends TlObject {

    public static final int ID = 863093588;

    public ArrayList<TlObject> dialogs;
	public ArrayList<TlObject> messages;
	public ArrayList<TlObject> chats;
	public ArrayList<TlObject> users;
	public TlObject state;

    public PeerDialogs(ArrayList<TlObject> dialogs, ArrayList<TlObject> messages, ArrayList<TlObject> chats, ArrayList<TlObject> users, TlObject state) {
        this.dialogs = dialogs;
		this.messages = messages;
		this.chats = chats;
		this.users = users;
		this.state = state;
    }

    public static PeerDialogs read(ByteArrayInputStream bytes) throws IOException {
        ArrayList<TlObject> dialogs = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		ArrayList<TlObject> messages = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		ArrayList<TlObject> chats = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		ArrayList<TlObject> users = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		TlObject state = TlObject.read(bytes);
		
		return new PeerDialogs(dialogs, messages, chats, users, state);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new VectorPrimitive(this.dialogs).write());
		bOut.write(new VectorPrimitive(this.messages).write());
		bOut.write(new VectorPrimitive(this.chats).write());
		bOut.write(new VectorPrimitive(this.users).write());
		bOut.write(this.state.write());
		
		return bOut.toByteArray();
    }
}
