//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class PeerChannel extends TlObject {

    public static final int ID = -1566230754;

    public long channel_id;

    public PeerChannel(long channel_id) {
        this.channel_id = channel_id;
    }

    public static PeerChannel read(ByteArrayInputStream bytes) throws IOException {
        long channel_id = LongPrimitive.read(bytes).getValue();
		
		return new PeerChannel(channel_id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new LongPrimitive(this.channel_id).write());
		
		return bOut.toByteArray();
    }
}
