//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class PeerNotifySettings extends TlObject {

    public static final int ID = -1472527322;

    public TlObject show_previews;
	public TlObject silent;
	public int mute_until;
	public TlObject ios_sound;
	public TlObject android_sound;
	public TlObject other_sound;

    public PeerNotifySettings(TlObject show_previews, TlObject silent, int mute_until, TlObject ios_sound, TlObject android_sound, TlObject other_sound) {
        this.show_previews = show_previews;
		this.silent = silent;
		this.mute_until = mute_until;
		this.ios_sound = ios_sound;
		this.android_sound = android_sound;
		this.other_sound = other_sound;
    }

    public static PeerNotifySettings read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		TlObject show_previews = (flags & (1 << 0)) != 0 ?  TlObject.read(bytes) : null;
		TlObject silent = (flags & (1 << 1)) != 0 ?  TlObject.read(bytes) : null;
		int mute_until = (flags & (1 << 2)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		TlObject ios_sound = (flags & (1 << 3)) != 0 ?  TlObject.read(bytes) : null;
		TlObject android_sound = (flags & (1 << 4)) != 0 ?  TlObject.read(bytes) : null;
		TlObject other_sound = (flags & (1 << 5)) != 0 ?  TlObject.read(bytes) : null;
		
		return new PeerNotifySettings(show_previews, silent, mute_until, ios_sound, android_sound, other_sound);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= (this.show_previews != null) ? (1 << 0) : 0;
		flags |= (this.silent != null) ? (1 << 1) : 0;
		flags |= (this.mute_until != 0) ? (1 << 2) : 0;
		flags |= (this.ios_sound != null) ? (1 << 3) : 0;
		flags |= (this.android_sound != null) ? (1 << 4) : 0;
		flags |= (this.other_sound != null) ? (1 << 5) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		if(this.show_previews != null)
			bOut.write(this.show_previews.write());
		if(this.silent != null)
			bOut.write(this.silent.write());
		if(this.mute_until != 0)
			bOut.write(new IntPrimitive(this.mute_until).write());
		if(this.ios_sound != null)
			bOut.write(this.ios_sound.write());
		if(this.android_sound != null)
			bOut.write(this.android_sound.write());
		if(this.other_sound != null)
			bOut.write(this.other_sound.write());
		
		return bOut.toByteArray();
    }
}
