//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.photos;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class PhotosSlice extends TlObject {

    public static final int ID = 352657236;

    public int count;
	public ArrayList<TlObject> photos;
	public ArrayList<TlObject> users;

    public PhotosSlice(int count, ArrayList<TlObject> photos, ArrayList<TlObject> users) {
        this.count = count;
		this.photos = photos;
		this.users = users;
    }

    public static PhotosSlice read(ByteArrayInputStream bytes) throws IOException {
        int count = IntPrimitive.read(bytes).getValue();
		ArrayList<TlObject> photos = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		ArrayList<TlObject> users = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		
		return new PhotosSlice(count, photos, users);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new IntPrimitive(this.count).write());
		bOut.write(new VectorPrimitive(this.photos).write());
		bOut.write(new VectorPrimitive(this.users).write());
		
		return bOut.toByteArray();
    }
}
