//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.account;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class PrivacyRules extends TlObject {

    public static final int ID = 1352683077;

    public ArrayList<TlObject> rules;
	public ArrayList<TlObject> chats;
	public ArrayList<TlObject> users;

    public PrivacyRules(ArrayList<TlObject> rules, ArrayList<TlObject> chats, ArrayList<TlObject> users) {
        this.rules = rules;
		this.chats = chats;
		this.users = users;
    }

    public static PrivacyRules read(ByteArrayInputStream bytes) throws IOException {
        ArrayList<TlObject> rules = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		ArrayList<TlObject> chats = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		ArrayList<TlObject> users = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		
		return new PrivacyRules(rules, chats, users);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new VectorPrimitive(this.rules).write());
		bOut.write(new VectorPrimitive(this.chats).write());
		bOut.write(new VectorPrimitive(this.users).write());
		
		return bOut.toByteArray();
    }
}
