//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ReactionCustomEmoji extends TlObject {

    public static final int ID = -1992950669;

    public long document_id;

    public ReactionCustomEmoji(long document_id) {
        this.document_id = document_id;
    }

    public static ReactionCustomEmoji read(ByteArrayInputStream bytes) throws IOException {
        long document_id = LongPrimitive.read(bytes).getValue();
		
		return new ReactionCustomEmoji(document_id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new LongPrimitive(this.document_id).write());
		
		return bOut.toByteArray();
    }
}
