//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class RequestPeerTypeChat extends TlObject {

    public static final int ID = -906990053;

    public boolean creator;
	public boolean bot_participant;
	public TlObject has_username;
	public TlObject forum;
	public TlObject user_admin_rights;
	public TlObject bot_admin_rights;

    public RequestPeerTypeChat(boolean creator, boolean bot_participant, TlObject has_username, TlObject forum, TlObject user_admin_rights, TlObject bot_admin_rights) {
        this.creator = creator;
		this.bot_participant = bot_participant;
		this.has_username = has_username;
		this.forum = forum;
		this.user_admin_rights = user_admin_rights;
		this.bot_admin_rights = bot_admin_rights;
    }

    public static RequestPeerTypeChat read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean creator = (flags & (1 << 0)) != 0;
		boolean bot_participant = (flags & (1 << 5)) != 0;
		TlObject has_username = (flags & (1 << 3)) != 0 ?  TlObject.read(bytes) : null;
		TlObject forum = (flags & (1 << 4)) != 0 ?  TlObject.read(bytes) : null;
		TlObject user_admin_rights = (flags & (1 << 1)) != 0 ?  TlObject.read(bytes) : null;
		TlObject bot_admin_rights = (flags & (1 << 2)) != 0 ?  TlObject.read(bytes) : null;
		
		return new RequestPeerTypeChat(creator, bot_participant, has_username, forum, user_admin_rights, bot_admin_rights);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.creator ? (1 << 0) : 0;
		flags |= this.bot_participant ? (1 << 5) : 0;
		flags |= (this.has_username != null) ? (1 << 3) : 0;
		flags |= (this.forum != null) ? (1 << 4) : 0;
		flags |= (this.user_admin_rights != null) ? (1 << 1) : 0;
		flags |= (this.bot_admin_rights != null) ? (1 << 2) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		if(this.has_username != null)
			bOut.write(this.has_username.write());
		if(this.forum != null)
			bOut.write(this.forum.write());
		if(this.user_admin_rights != null)
			bOut.write(this.user_admin_rights.write());
		if(this.bot_admin_rights != null)
			bOut.write(this.bot_admin_rights.write());
		
		return bOut.toByteArray();
    }
}
