//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.account;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class SavedRingtones extends TlObject {

    public static final int ID = -1041683259;

    public long hash;
	public ArrayList<TlObject> ringtones;

    public SavedRingtones(long hash, ArrayList<TlObject> ringtones) {
        this.hash = hash;
		this.ringtones = ringtones;
    }

    public static SavedRingtones read(ByteArrayInputStream bytes) throws IOException {
        long hash = LongPrimitive.read(bytes).getValue();
		ArrayList<TlObject> ringtones = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		
		return new SavedRingtones(hash, ringtones);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new LongPrimitive(this.hash).write());
		bOut.write(new VectorPrimitive(this.ringtones).write());
		
		return bOut.toByteArray();
    }
}
