//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class SavedGifs extends TlObject {

    public static final int ID = -2069878259;

    public long hash;
	public ArrayList<TlObject> gifs;

    public SavedGifs(long hash, ArrayList<TlObject> gifs) {
        this.hash = hash;
		this.gifs = gifs;
    }

    public static SavedGifs read(ByteArrayInputStream bytes) throws IOException {
        long hash = LongPrimitive.read(bytes).getValue();
		ArrayList<TlObject> gifs = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		
		return new SavedGifs(hash, gifs);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new LongPrimitive(this.hash).write());
		bOut.write(new VectorPrimitive(this.gifs).write());
		
		return bOut.toByteArray();
    }
}
