//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class SecurePlainPhone extends TlObject {

    public static final int ID = 2103482845;

    public String phone;

    public SecurePlainPhone(String phone) {
        this.phone = phone;
    }

    public static SecurePlainPhone read(ByteArrayInputStream bytes) throws IOException {
        String phone = StringPrimitive.read(bytes).getValue();
		
		return new SecurePlainPhone(phone);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new StringPrimitive(this.phone).write());
		
		return bOut.toByteArray();
    }
}
