//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.auth;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class SentCodeTypeFragmentSms extends TlObject {

    public static final int ID = -648651719;

    public String url;
	public int length;

    public SentCodeTypeFragmentSms(String url, int length) {
        this.url = url;
		this.length = length;
    }

    public static SentCodeTypeFragmentSms read(ByteArrayInputStream bytes) throws IOException {
        String url = StringPrimitive.read(bytes).getValue();
		int length = IntPrimitive.read(bytes).getValue();
		
		return new SentCodeTypeFragmentSms(url, length);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new StringPrimitive(this.url).write());
		bOut.write(new IntPrimitive(this.length).write());
		
		return bOut.toByteArray();
    }
}
