//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class SentEncryptedFile extends TlObject {

    public static final int ID = -1802240206;

    public int date;
	public TlObject file;

    public SentEncryptedFile(int date, TlObject file) {
        this.date = date;
		this.file = file;
    }

    public static SentEncryptedFile read(ByteArrayInputStream bytes) throws IOException {
        int date = IntPrimitive.read(bytes).getValue();
		TlObject file = TlObject.read(bytes);
		
		return new SentEncryptedFile(date, file);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new IntPrimitive(this.date).write());
		bOut.write(this.file.write());
		
		return bOut.toByteArray();
    }
}
