//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class SponsoredMessages extends TlObject {

    public static final int ID = -907141753;

    public int posts_between;
	public ArrayList<TlObject> messages;
	public ArrayList<TlObject> chats;
	public ArrayList<TlObject> users;

    public SponsoredMessages(int posts_between, ArrayList<TlObject> messages, ArrayList<TlObject> chats, ArrayList<TlObject> users) {
        this.posts_between = posts_between;
		this.messages = messages;
		this.chats = chats;
		this.users = users;
    }

    public static SponsoredMessages read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		int posts_between = (flags & (1 << 0)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		ArrayList<TlObject> messages = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		ArrayList<TlObject> chats = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		ArrayList<TlObject> users = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		
		return new SponsoredMessages(posts_between, messages, chats, users);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= (this.posts_between != 0) ? (1 << 0) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		if(this.posts_between != 0)
			bOut.write(new IntPrimitive(this.posts_between).write());
		bOut.write(new VectorPrimitive(this.messages).write());
		bOut.write(new VectorPrimitive(this.chats).write());
		bOut.write(new VectorPrimitive(this.users).write());
		
		return bOut.toByteArray();
    }
}
