//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class StatsDateRangeDays extends TlObject {

    public static final int ID = -1237848657;

    public int min_date;
	public int max_date;

    public StatsDateRangeDays(int min_date, int max_date) {
        this.min_date = min_date;
		this.max_date = max_date;
    }

    public static StatsDateRangeDays read(ByteArrayInputStream bytes) throws IOException {
        int min_date = IntPrimitive.read(bytes).getValue();
		int max_date = IntPrimitive.read(bytes).getValue();
		
		return new StatsDateRangeDays(min_date, max_date);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new IntPrimitive(this.min_date).write());
		bOut.write(new IntPrimitive(this.max_date).write());
		
		return bOut.toByteArray();
    }
}
