//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class StatsPercentValue extends TlObject {

    public static final int ID = -875679776;

    public TlObject part;
	public TlObject total;

    public StatsPercentValue(TlObject part, TlObject total) {
        this.part = part;
		this.total = total;
    }

    public static StatsPercentValue read(ByteArrayInputStream bytes) throws IOException {
        TlObject part = TlObject.read(bytes);
		TlObject total = TlObject.read(bytes);
		
		return new StatsPercentValue(part, total);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.part.write());
		bOut.write(this.total.write());
		
		return bOut.toByteArray();
    }
}
