//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class StickerSetMultiCovered extends TlObject {

    public static final int ID = 872932635;

    public TlObject set;
	public ArrayList<TlObject> covers;

    public StickerSetMultiCovered(TlObject set, ArrayList<TlObject> covers) {
        this.set = set;
		this.covers = covers;
    }

    public static StickerSetMultiCovered read(ByteArrayInputStream bytes) throws IOException {
        TlObject set = TlObject.read(bytes);
		ArrayList<TlObject> covers = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		
		return new StickerSetMultiCovered(set, covers);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.set.write());
		bOut.write(new VectorPrimitive(this.covers).write());
		
		return bOut.toByteArray();
    }
}
