//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class TextImage extends TlObject {

    public static final int ID = 136105807;

    public long document_id;
	public int w;
	public int h;

    public TextImage(long document_id, int w, int h) {
        this.document_id = document_id;
		this.w = w;
		this.h = h;
    }

    public static TextImage read(ByteArrayInputStream bytes) throws IOException {
        long document_id = LongPrimitive.read(bytes).getValue();
		int w = IntPrimitive.read(bytes).getValue();
		int h = IntPrimitive.read(bytes).getValue();
		
		return new TextImage(document_id, w, h);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new LongPrimitive(this.document_id).write());
		bOut.write(new IntPrimitive(this.w).write());
		bOut.write(new IntPrimitive(this.h).write());
		
		return bOut.toByteArray();
    }
}
