//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UpdateStickerSets extends TlObject {

    public static final int ID = 834816008;

    public boolean masks;
	public boolean emojis;

    public UpdateStickerSets(boolean masks, boolean emojis) {
        this.masks = masks;
		this.emojis = emojis;
    }

    public static UpdateStickerSets read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean masks = (flags & (1 << 0)) != 0;
		boolean emojis = (flags & (1 << 1)) != 0;
		
		return new UpdateStickerSets(masks, emojis);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.masks ? (1 << 0) : 0;
		flags |= this.emojis ? (1 << 1) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		
		return bOut.toByteArray();
    }
}
