//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UpdateEncryptedChatTyping extends TlObject {

    public static final int ID = 386986326;

    public int chat_id;

    public UpdateEncryptedChatTyping(int chat_id) {
        this.chat_id = chat_id;
    }

    public static UpdateEncryptedChatTyping read(ByteArrayInputStream bytes) throws IOException {
        int chat_id = IntPrimitive.read(bytes).getValue();
		
		return new UpdateEncryptedChatTyping(chat_id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new IntPrimitive(this.chat_id).write());
		
		return bOut.toByteArray();
    }
}
