//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UpdatePrivacy extends TlObject {

    public static final int ID = -298113238;

    public TlObject key;
	public ArrayList<TlObject> rules;

    public UpdatePrivacy(TlObject key, ArrayList<TlObject> rules) {
        this.key = key;
		this.rules = rules;
    }

    public static UpdatePrivacy read(ByteArrayInputStream bytes) throws IOException {
        TlObject key = TlObject.read(bytes);
		ArrayList<TlObject> rules = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		
		return new UpdatePrivacy(key, rules);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.key.write());
		bOut.write(new VectorPrimitive(this.rules).write());
		
		return bOut.toByteArray();
    }
}
