//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UpdateMessageID extends TlObject {

    public static final int ID = 1318109142;

    public int id;
	public long random_id;

    public UpdateMessageID(int id, long random_id) {
        this.id = id;
		this.random_id = random_id;
    }

    public static UpdateMessageID read(ByteArrayInputStream bytes) throws IOException {
        int id = IntPrimitive.read(bytes).getValue();
		long random_id = LongPrimitive.read(bytes).getValue();
		
		return new UpdateMessageID(id, random_id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new IntPrimitive(this.id).write());
		bOut.write(new LongPrimitive(this.random_id).write());
		
		return bOut.toByteArray();
    }
}
