//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UpdateReadChannelDiscussionInbox extends TlObject {

    public static final int ID = -693004986;

    public long channel_id;
	public int top_msg_id;
	public int read_max_id;
	public long broadcast_id;
	public int broadcast_post;

    public UpdateReadChannelDiscussionInbox(long channel_id, int top_msg_id, int read_max_id, long broadcast_id, int broadcast_post) {
        this.channel_id = channel_id;
		this.top_msg_id = top_msg_id;
		this.read_max_id = read_max_id;
		this.broadcast_id = broadcast_id;
		this.broadcast_post = broadcast_post;
    }

    public static UpdateReadChannelDiscussionInbox read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		long channel_id = LongPrimitive.read(bytes).getValue();
		int top_msg_id = IntPrimitive.read(bytes).getValue();
		int read_max_id = IntPrimitive.read(bytes).getValue();
		long broadcast_id = (flags & (1 << 0)) != 0 ?  LongPrimitive.read(bytes).getValue() : 0;
		int broadcast_post = (flags & (1 << 0)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		
		return new UpdateReadChannelDiscussionInbox(channel_id, top_msg_id, read_max_id, broadcast_id, broadcast_post);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= (this.broadcast_id != 0) ? (1 << 0) : 0;
		flags |= (this.broadcast_post != 0) ? (1 << 0) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new LongPrimitive(this.channel_id).write());
		bOut.write(new IntPrimitive(this.top_msg_id).write());
		bOut.write(new IntPrimitive(this.read_max_id).write());
		if(this.broadcast_id != 0)
			bOut.write(new LongPrimitive(this.broadcast_id).write());
		if(this.broadcast_post != 0)
			bOut.write(new IntPrimitive(this.broadcast_post).write());
		
		return bOut.toByteArray();
    }
}
