//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UpdateUserEmojiStatus extends TlObject {

    public static final int ID = 674706841;

    public long user_id;
	public TlObject emoji_status;

    public UpdateUserEmojiStatus(long user_id, TlObject emoji_status) {
        this.user_id = user_id;
		this.emoji_status = emoji_status;
    }

    public static UpdateUserEmojiStatus read(ByteArrayInputStream bytes) throws IOException {
        long user_id = LongPrimitive.read(bytes).getValue();
		TlObject emoji_status = TlObject.read(bytes);
		
		return new UpdateUserEmojiStatus(user_id, emoji_status);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new LongPrimitive(this.user_id).write());
		bOut.write(this.emoji_status.write());
		
		return bOut.toByteArray();
    }
}
