//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UpdateReadHistoryOutbox extends TlObject {

    public static final int ID = 791617983;

    public TlObject peer;
	public int max_id;
	public int pts;
	public int pts_count;

    public UpdateReadHistoryOutbox(TlObject peer, int max_id, int pts, int pts_count) {
        this.peer = peer;
		this.max_id = max_id;
		this.pts = pts;
		this.pts_count = pts_count;
    }

    public static UpdateReadHistoryOutbox read(ByteArrayInputStream bytes) throws IOException {
        TlObject peer = TlObject.read(bytes);
		int max_id = IntPrimitive.read(bytes).getValue();
		int pts = IntPrimitive.read(bytes).getValue();
		int pts_count = IntPrimitive.read(bytes).getValue();
		
		return new UpdateReadHistoryOutbox(peer, max_id, pts, pts_count);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.peer.write());
		bOut.write(new IntPrimitive(this.max_id).write());
		bOut.write(new IntPrimitive(this.pts).write());
		bOut.write(new IntPrimitive(this.pts_count).write());
		
		return bOut.toByteArray();
    }
}
