//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UpdateMoveStickerSetToTop extends TlObject {

    public static final int ID = -2030252155;

    public boolean masks;
	public boolean emojis;
	public long stickerset;

    public UpdateMoveStickerSetToTop(boolean masks, boolean emojis, long stickerset) {
        this.masks = masks;
		this.emojis = emojis;
		this.stickerset = stickerset;
    }

    public static UpdateMoveStickerSetToTop read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean masks = (flags & (1 << 0)) != 0;
		boolean emojis = (flags & (1 << 1)) != 0;
		long stickerset = LongPrimitive.read(bytes).getValue();
		
		return new UpdateMoveStickerSetToTop(masks, emojis, stickerset);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.masks ? (1 << 0) : 0;
		flags |= this.emojis ? (1 << 1) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new LongPrimitive(this.stickerset).write());
		
		return bOut.toByteArray();
    }
}
