//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UpdateMessageReactions extends TlObject {

    public static final int ID = 1578843320;

    public TlObject peer;
	public int msg_id;
	public int top_msg_id;
	public TlObject reactions;

    public UpdateMessageReactions(TlObject peer, int msg_id, int top_msg_id, TlObject reactions) {
        this.peer = peer;
		this.msg_id = msg_id;
		this.top_msg_id = top_msg_id;
		this.reactions = reactions;
    }

    public static UpdateMessageReactions read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		TlObject peer = TlObject.read(bytes);
		int msg_id = IntPrimitive.read(bytes).getValue();
		int top_msg_id = (flags & (1 << 0)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		TlObject reactions = TlObject.read(bytes);
		
		return new UpdateMessageReactions(peer, msg_id, top_msg_id, reactions);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= (this.top_msg_id != 0) ? (1 << 0) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(this.peer.write());
		bOut.write(new IntPrimitive(this.msg_id).write());
		if(this.top_msg_id != 0)
			bOut.write(new IntPrimitive(this.top_msg_id).write());
		bOut.write(this.reactions.write());
		
		return bOut.toByteArray();
    }
}
