//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UpdateChannelTooLong extends TlObject {

    public static final int ID = 277713951;

    public long channel_id;
	public int pts;

    public UpdateChannelTooLong(long channel_id, int pts) {
        this.channel_id = channel_id;
		this.pts = pts;
    }

    public static UpdateChannelTooLong read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		long channel_id = LongPrimitive.read(bytes).getValue();
		int pts = (flags & (1 << 0)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		
		return new UpdateChannelTooLong(channel_id, pts);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= (this.pts != 0) ? (1 << 0) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new LongPrimitive(this.channel_id).write());
		if(this.pts != 0)
			bOut.write(new IntPrimitive(this.pts).write());
		
		return bOut.toByteArray();
    }
}
