//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UpdateChatUserTyping extends TlObject {

    public static final int ID = -2092401936;

    public long chat_id;
	public TlObject from_id;
	public TlObject action;

    public UpdateChatUserTyping(long chat_id, TlObject from_id, TlObject action) {
        this.chat_id = chat_id;
		this.from_id = from_id;
		this.action = action;
    }

    public static UpdateChatUserTyping read(ByteArrayInputStream bytes) throws IOException {
        long chat_id = LongPrimitive.read(bytes).getValue();
		TlObject from_id = TlObject.read(bytes);
		TlObject action = TlObject.read(bytes);
		
		return new UpdateChatUserTyping(chat_id, from_id, action);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new LongPrimitive(this.chat_id).write());
		bOut.write(this.from_id.write());
		bOut.write(this.action.write());
		
		return bOut.toByteArray();
    }
}
