//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UpdateChannelMessageViews extends TlObject {

    public static final int ID = -232346616;

    public long channel_id;
	public int id;
	public int views;

    public UpdateChannelMessageViews(long channel_id, int id, int views) {
        this.channel_id = channel_id;
		this.id = id;
		this.views = views;
    }

    public static UpdateChannelMessageViews read(ByteArrayInputStream bytes) throws IOException {
        long channel_id = LongPrimitive.read(bytes).getValue();
		int id = IntPrimitive.read(bytes).getValue();
		int views = IntPrimitive.read(bytes).getValue();
		
		return new UpdateChannelMessageViews(channel_id, id, views);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new LongPrimitive(this.channel_id).write());
		bOut.write(new IntPrimitive(this.id).write());
		bOut.write(new IntPrimitive(this.views).write());
		
		return bOut.toByteArray();
    }
}
