//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UpdateUserPhone extends TlObject {

    public static final int ID = 88680979;

    public long user_id;
	public String phone;

    public UpdateUserPhone(long user_id, String phone) {
        this.user_id = user_id;
		this.phone = phone;
    }

    public static UpdateUserPhone read(ByteArrayInputStream bytes) throws IOException {
        long user_id = LongPrimitive.read(bytes).getValue();
		String phone = StringPrimitive.read(bytes).getValue();
		
		return new UpdateUserPhone(user_id, phone);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new LongPrimitive(this.user_id).write());
		bOut.write(new StringPrimitive(this.phone).write());
		
		return bOut.toByteArray();
    }
}
