//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UpdateChannelWebPage extends TlObject {

    public static final int ID = 791390623;

    public long channel_id;
	public TlObject webpage;
	public int pts;
	public int pts_count;

    public UpdateChannelWebPage(long channel_id, TlObject webpage, int pts, int pts_count) {
        this.channel_id = channel_id;
		this.webpage = webpage;
		this.pts = pts;
		this.pts_count = pts_count;
    }

    public static UpdateChannelWebPage read(ByteArrayInputStream bytes) throws IOException {
        long channel_id = LongPrimitive.read(bytes).getValue();
		TlObject webpage = TlObject.read(bytes);
		int pts = IntPrimitive.read(bytes).getValue();
		int pts_count = IntPrimitive.read(bytes).getValue();
		
		return new UpdateChannelWebPage(channel_id, webpage, pts, pts_count);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new LongPrimitive(this.channel_id).write());
		bOut.write(this.webpage.write());
		bOut.write(new IntPrimitive(this.pts).write());
		bOut.write(new IntPrimitive(this.pts_count).write());
		
		return bOut.toByteArray();
    }
}
