//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UrlAuthResultRequest extends TlObject {

    public static final int ID = -1831650802;

    public boolean request_write_access;
	public TlObject bot;
	public String domain;

    public UrlAuthResultRequest(boolean request_write_access, TlObject bot, String domain) {
        this.request_write_access = request_write_access;
		this.bot = bot;
		this.domain = domain;
    }

    public static UrlAuthResultRequest read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean request_write_access = (flags & (1 << 0)) != 0;
		TlObject bot = TlObject.read(bytes);
		String domain = StringPrimitive.read(bytes).getValue();
		
		return new UrlAuthResultRequest(request_write_access, bot, domain);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.request_write_access ? (1 << 0) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(this.bot.write());
		bOut.write(new StringPrimitive(this.domain).write());
		
		return bOut.toByteArray();
    }
}
