//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class Username extends TlObject {

    public static final int ID = -1274595769;

    public boolean editable;
	public boolean active;
	public String username;

    public Username(boolean editable, boolean active, String username) {
        this.editable = editable;
		this.active = active;
		this.username = username;
    }

    public static Username read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean editable = (flags & (1 << 0)) != 0;
		boolean active = (flags & (1 << 1)) != 0;
		String username = StringPrimitive.read(bytes).getValue();
		
		return new Username(editable, active, username);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.editable ? (1 << 0) : 0;
		flags |= this.active ? (1 << 1) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new StringPrimitive(this.username).write());
		
		return bOut.toByteArray();
    }
}
