//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UserProfilePhoto extends TlObject {

    public static final int ID = -2100168954;

    public boolean has_video;
	public boolean personal;
	public long photo_id;
	public byte[] stripped_thumb;
	public int dc_id;

    public UserProfilePhoto(boolean has_video, boolean personal, long photo_id, byte[] stripped_thumb, int dc_id) {
        this.has_video = has_video;
		this.personal = personal;
		this.photo_id = photo_id;
		this.stripped_thumb = stripped_thumb;
		this.dc_id = dc_id;
    }

    public static UserProfilePhoto read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean has_video = (flags & (1 << 0)) != 0;
		boolean personal = (flags & (1 << 2)) != 0;
		long photo_id = LongPrimitive.read(bytes).getValue();
		byte[] stripped_thumb = (flags & (1 << 1)) != 0 ?  BytesPrimitive.read(bytes).getValue() : null;
		int dc_id = IntPrimitive.read(bytes).getValue();
		
		return new UserProfilePhoto(has_video, personal, photo_id, stripped_thumb, dc_id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.has_video ? (1 << 0) : 0;
		flags |= this.personal ? (1 << 2) : 0;
		flags |= (this.stripped_thumb != null) ? (1 << 1) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new LongPrimitive(this.photo_id).write());
		if(this.stripped_thumb != null)
			bOut.write(new BytesPrimitive(this.stripped_thumb).write());
		bOut.write(new IntPrimitive(this.dc_id).write());
		
		return bOut.toByteArray();
    }
}
