//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UserStatusOffline extends TlObject {

    public static final int ID = 9203775;

    public int was_online;

    public UserStatusOffline(int was_online) {
        this.was_online = was_online;
    }

    public static UserStatusOffline read(ByteArrayInputStream bytes) throws IOException {
        int was_online = IntPrimitive.read(bytes).getValue();
		
		return new UserStatusOffline(was_online);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new IntPrimitive(this.was_online).write());
		
		return bOut.toByteArray();
    }
}
