//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.types;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class WebPage extends TlObject {

    public static final int ID = -392411726;

    public long id;
	public String url;
	public String display_url;
	public int hash;
	public String type;
	public String site_name;
	public String title;
	public String description;
	public TlObject photo;
	public String embed_url;
	public String embed_type;
	public int embed_width;
	public int embed_height;
	public int duration;
	public String author;
	public TlObject document;
	public TlObject cached_page;
	public ArrayList<TlObject> attributes;

    public WebPage(long id, String url, String display_url, int hash, String type, String site_name, String title, String description, TlObject photo, String embed_url, String embed_type, int embed_width, int embed_height, int duration, String author, TlObject document, TlObject cached_page, ArrayList<TlObject> attributes) {
        this.id = id;
		this.url = url;
		this.display_url = display_url;
		this.hash = hash;
		this.type = type;
		this.site_name = site_name;
		this.title = title;
		this.description = description;
		this.photo = photo;
		this.embed_url = embed_url;
		this.embed_type = embed_type;
		this.embed_width = embed_width;
		this.embed_height = embed_height;
		this.duration = duration;
		this.author = author;
		this.document = document;
		this.cached_page = cached_page;
		this.attributes = attributes;
    }

    public static WebPage read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		long id = LongPrimitive.read(bytes).getValue();
		String url = StringPrimitive.read(bytes).getValue();
		String display_url = StringPrimitive.read(bytes).getValue();
		int hash = IntPrimitive.read(bytes).getValue();
		String type = (flags & (1 << 0)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		String site_name = (flags & (1 << 1)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		String title = (flags & (1 << 2)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		String description = (flags & (1 << 3)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		TlObject photo = (flags & (1 << 4)) != 0 ?  TlObject.read(bytes) : null;
		String embed_url = (flags & (1 << 5)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		String embed_type = (flags & (1 << 5)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		int embed_width = (flags & (1 << 6)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		int embed_height = (flags & (1 << 6)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		int duration = (flags & (1 << 7)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		String author = (flags & (1 << 8)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		TlObject document = (flags & (1 << 9)) != 0 ?  TlObject.read(bytes) : null;
		TlObject cached_page = (flags & (1 << 10)) != 0 ?  TlObject.read(bytes) : null;
		ArrayList<TlObject> attributes = (flags & (1 << 12)) != 0 ?  ((VectorPrimitive)TlObject.read(bytes)).getValue() : null;
		
		return new WebPage(id, url, display_url, hash, type, site_name, title, description, photo, embed_url, embed_type, embed_width, embed_height, duration, author, document, cached_page, attributes);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= (this.type != null) ? (1 << 0) : 0;
		flags |= (this.site_name != null) ? (1 << 1) : 0;
		flags |= (this.title != null) ? (1 << 2) : 0;
		flags |= (this.description != null) ? (1 << 3) : 0;
		flags |= (this.photo != null) ? (1 << 4) : 0;
		flags |= (this.embed_url != null) ? (1 << 5) : 0;
		flags |= (this.embed_type != null) ? (1 << 5) : 0;
		flags |= (this.embed_width != 0) ? (1 << 6) : 0;
		flags |= (this.embed_height != 0) ? (1 << 6) : 0;
		flags |= (this.duration != 0) ? (1 << 7) : 0;
		flags |= (this.author != null) ? (1 << 8) : 0;
		flags |= (this.document != null) ? (1 << 9) : 0;
		flags |= (this.cached_page != null) ? (1 << 10) : 0;
		flags |= (this.attributes != null) ? (1 << 12) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new LongPrimitive(this.id).write());
		bOut.write(new StringPrimitive(this.url).write());
		bOut.write(new StringPrimitive(this.display_url).write());
		bOut.write(new IntPrimitive(this.hash).write());
		if(this.type != null)
			bOut.write(new StringPrimitive(this.type).write());
		if(this.site_name != null)
			bOut.write(new StringPrimitive(this.site_name).write());
		if(this.title != null)
			bOut.write(new StringPrimitive(this.title).write());
		if(this.description != null)
			bOut.write(new StringPrimitive(this.description).write());
		if(this.photo != null)
			bOut.write(this.photo.write());
		if(this.embed_url != null)
			bOut.write(new StringPrimitive(this.embed_url).write());
		if(this.embed_type != null)
			bOut.write(new StringPrimitive(this.embed_type).write());
		if(this.embed_width != 0)
			bOut.write(new IntPrimitive(this.embed_width).write());
		if(this.embed_height != 0)
			bOut.write(new IntPrimitive(this.embed_height).write());
		if(this.duration != 0)
			bOut.write(new IntPrimitive(this.duration).write());
		if(this.author != null)
			bOut.write(new StringPrimitive(this.author).write());
		if(this.document != null)
			bOut.write(this.document.write());
		if(this.cached_page != null)
			bOut.write(this.cached_page.write());
		if(this.attributes != null)
			bOut.write(new VectorPrimitive(this.attributes).write());
		
		return bOut.toByteArray();
    }
}
