//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class AcceptEncryption extends TlObject {

    public static final int ID = 1035731989;

    public TlObject peer;
	public byte[] g_b;
	public long key_fingerprint;

    public AcceptEncryption(TlObject peer, byte[] g_b, long key_fingerprint) {
        this.peer = peer;
		this.g_b = g_b;
		this.key_fingerprint = key_fingerprint;
    }

    public static AcceptEncryption read(ByteArrayInputStream bytes) throws IOException {
        TlObject peer = TlObject.read(bytes);
		byte[] g_b = BytesPrimitive.read(bytes).getValue();
		long key_fingerprint = LongPrimitive.read(bytes).getValue();
		
		return new AcceptEncryption(peer, g_b, key_fingerprint);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.peer.write());
		bOut.write(new BytesPrimitive(this.g_b).write());
		bOut.write(new LongPrimitive(this.key_fingerprint).write());
		
		return bOut.toByteArray();
    }
}
