//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class CheckChatInvite extends TlObject {

    public static final int ID = 1051570619;

    public String hash;

    public CheckChatInvite(String hash) {
        this.hash = hash;
    }

    public static CheckChatInvite read(ByteArrayInputStream bytes) throws IOException {
        String hash = StringPrimitive.read(bytes).getValue();
		
		return new CheckChatInvite(hash);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new StringPrimitive(this.hash).write());
		
		return bOut.toByteArray();
    }
}
