//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class CreateChat extends TlObject {

    public static final int ID = 3450904;

    public ArrayList<TlObject> users;
	public String title;
	public int ttl_period;

    public CreateChat(ArrayList<TlObject> users, String title, int ttl_period) {
        this.users = users;
		this.title = title;
		this.ttl_period = ttl_period;
    }

    public static CreateChat read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		ArrayList<TlObject> users = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		String title = StringPrimitive.read(bytes).getValue();
		int ttl_period = (flags & (1 << 0)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		
		return new CreateChat(users, title, ttl_period);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= (this.ttl_period != 0) ? (1 << 0) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new VectorPrimitive(this.users).write());
		bOut.write(new StringPrimitive(this.title).write());
		if(this.ttl_period != 0)
			bOut.write(new IntPrimitive(this.ttl_period).write());
		
		return bOut.toByteArray();
    }
}
