//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class EditChatTitle extends TlObject {

    public static final int ID = 1937260541;

    public long chat_id;
	public String title;

    public EditChatTitle(long chat_id, String title) {
        this.chat_id = chat_id;
		this.title = title;
    }

    public static EditChatTitle read(ByteArrayInputStream bytes) throws IOException {
        long chat_id = LongPrimitive.read(bytes).getValue();
		String title = StringPrimitive.read(bytes).getValue();
		
		return new EditChatTitle(chat_id, title);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new LongPrimitive(this.chat_id).write());
		bOut.write(new StringPrimitive(this.title).write());
		
		return bOut.toByteArray();
    }
}
