//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class GetAttachMenuBot extends TlObject {

    public static final int ID = 1998676370;

    public TlObject bot;

    public GetAttachMenuBot(TlObject bot) {
        this.bot = bot;
    }

    public static GetAttachMenuBot read(ByteArrayInputStream bytes) throws IOException {
        TlObject bot = TlObject.read(bytes);
		
		return new GetAttachMenuBot(bot);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.bot.write());
		
		return bOut.toByteArray();
    }
}
