//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class GetArchivedStickers extends TlObject {

    public static final int ID = 1475442322;

    public boolean masks;
	public boolean emojis;
	public long offset_id;
	public int limit;

    public GetArchivedStickers(boolean masks, boolean emojis, long offset_id, int limit) {
        this.masks = masks;
		this.emojis = emojis;
		this.offset_id = offset_id;
		this.limit = limit;
    }

    public static GetArchivedStickers read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean masks = (flags & (1 << 0)) != 0;
		boolean emojis = (flags & (1 << 1)) != 0;
		long offset_id = LongPrimitive.read(bytes).getValue();
		int limit = IntPrimitive.read(bytes).getValue();
		
		return new GetArchivedStickers(masks, emojis, offset_id, limit);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.masks ? (1 << 0) : 0;
		flags |= this.emojis ? (1 << 1) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new LongPrimitive(this.offset_id).write());
		bOut.write(new IntPrimitive(this.limit).write());
		
		return bOut.toByteArray();
    }
}
