//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class GetEmojiGroups extends TlObject {

    public static final int ID = 1955122779;

    public int hash;

    public GetEmojiGroups(int hash) {
        this.hash = hash;
    }

    public static GetEmojiGroups read(ByteArrayInputStream bytes) throws IOException {
        int hash = IntPrimitive.read(bytes).getValue();
		
		return new GetEmojiGroups(hash);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new IntPrimitive(this.hash).write());
		
		return bOut.toByteArray();
    }
}
