//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class GetInlineBotResults extends TlObject {

    public static final int ID = 1364105629;

    public TlObject bot;
	public TlObject peer;
	public TlObject geo_point;
	public String query;
	public String offset;

    public GetInlineBotResults(TlObject bot, TlObject peer, TlObject geo_point, String query, String offset) {
        this.bot = bot;
		this.peer = peer;
		this.geo_point = geo_point;
		this.query = query;
		this.offset = offset;
    }

    public static GetInlineBotResults read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		TlObject bot = TlObject.read(bytes);
		TlObject peer = TlObject.read(bytes);
		TlObject geo_point = (flags & (1 << 0)) != 0 ?  TlObject.read(bytes) : null;
		String query = StringPrimitive.read(bytes).getValue();
		String offset = StringPrimitive.read(bytes).getValue();
		
		return new GetInlineBotResults(bot, peer, geo_point, query, offset);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= (this.geo_point != null) ? (1 << 0) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(this.bot.write());
		bOut.write(this.peer.write());
		if(this.geo_point != null)
			bOut.write(this.geo_point.write());
		bOut.write(new StringPrimitive(this.query).write());
		bOut.write(new StringPrimitive(this.offset).write());
		
		return bOut.toByteArray();
    }
}
