//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class GetMessagesReactions extends TlObject {

    public static final int ID = -1950707482;

    public TlObject peer;
	public ArrayList<TlObject> id;

    public GetMessagesReactions(TlObject peer, ArrayList<TlObject> id) {
        this.peer = peer;
		this.id = id;
    }

    public static GetMessagesReactions read(ByteArrayInputStream bytes) throws IOException {
        TlObject peer = TlObject.read(bytes);
		ArrayList<TlObject> id = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		
		return new GetMessagesReactions(peer, id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.peer.write());
		bOut.write(new VectorPrimitive(this.id).write());
		
		return bOut.toByteArray();
    }
}
