//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class GetPinnedDialogs extends TlObject {

    public static final int ID = -692498958;

    public int folder_id;

    public GetPinnedDialogs(int folder_id) {
        this.folder_id = folder_id;
    }

    public static GetPinnedDialogs read(ByteArrayInputStream bytes) throws IOException {
        int folder_id = IntPrimitive.read(bytes).getValue();
		
		return new GetPinnedDialogs(folder_id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new IntPrimitive(this.folder_id).write());
		
		return bOut.toByteArray();
    }
}
