//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class GetSearchResultsPositions extends TlObject {

    public static final int ID = 1855292323;

    public TlObject peer;
	public TlObject filter;
	public int offset_id;
	public int limit;

    public GetSearchResultsPositions(TlObject peer, TlObject filter, int offset_id, int limit) {
        this.peer = peer;
		this.filter = filter;
		this.offset_id = offset_id;
		this.limit = limit;
    }

    public static GetSearchResultsPositions read(ByteArrayInputStream bytes) throws IOException {
        TlObject peer = TlObject.read(bytes);
		TlObject filter = TlObject.read(bytes);
		int offset_id = IntPrimitive.read(bytes).getValue();
		int limit = IntPrimitive.read(bytes).getValue();
		
		return new GetSearchResultsPositions(peer, filter, offset_id, limit);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.peer.write());
		bOut.write(this.filter.write());
		bOut.write(new IntPrimitive(this.offset_id).write());
		bOut.write(new IntPrimitive(this.limit).write());
		
		return bOut.toByteArray();
    }
}
