//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class HideChatJoinRequest extends TlObject {

    public static final int ID = 2145904661;

    public boolean approved;
	public TlObject peer;
	public TlObject user_id;

    public HideChatJoinRequest(boolean approved, TlObject peer, TlObject user_id) {
        this.approved = approved;
		this.peer = peer;
		this.user_id = user_id;
    }

    public static HideChatJoinRequest read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean approved = (flags & (1 << 0)) != 0;
		TlObject peer = TlObject.read(bytes);
		TlObject user_id = TlObject.read(bytes);
		
		return new HideChatJoinRequest(approved, peer, user_id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.approved ? (1 << 0) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(this.peer.write());
		bOut.write(this.user_id.write());
		
		return bOut.toByteArray();
    }
}
