//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class HideAllChatJoinRequests extends TlObject {

    public static final int ID = -528091926;

    public boolean approved;
	public TlObject peer;
	public String link;

    public HideAllChatJoinRequests(boolean approved, TlObject peer, String link) {
        this.approved = approved;
		this.peer = peer;
		this.link = link;
    }

    public static HideAllChatJoinRequests read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean approved = (flags & (1 << 0)) != 0;
		TlObject peer = TlObject.read(bytes);
		String link = (flags & (1 << 1)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		
		return new HideAllChatJoinRequests(approved, peer, link);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.approved ? (1 << 0) : 0;
		flags |= (this.link != null) ? (1 << 1) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(this.peer.write());
		if(this.link != null)
			bOut.write(new StringPrimitive(this.link).write());
		
		return bOut.toByteArray();
    }
}
