//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ReadHistory extends TlObject {

    public static final int ID = 238054714;

    public TlObject peer;
	public int max_id;

    public ReadHistory(TlObject peer, int max_id) {
        this.peer = peer;
		this.max_id = max_id;
    }

    public static ReadHistory read(ByteArrayInputStream bytes) throws IOException {
        TlObject peer = TlObject.read(bytes);
		int max_id = IntPrimitive.read(bytes).getValue();
		
		return new ReadHistory(peer, max_id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.peer.write());
		bOut.write(new IntPrimitive(this.max_id).write());
		
		return bOut.toByteArray();
    }
}
