//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ReadEncryptedHistory extends TlObject {

    public static final int ID = 2135648522;

    public TlObject peer;
	public int max_date;

    public ReadEncryptedHistory(TlObject peer, int max_date) {
        this.peer = peer;
		this.max_date = max_date;
    }

    public static ReadEncryptedHistory read(ByteArrayInputStream bytes) throws IOException {
        TlObject peer = TlObject.read(bytes);
		int max_date = IntPrimitive.read(bytes).getValue();
		
		return new ReadEncryptedHistory(peer, max_date);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.peer.write());
		bOut.write(new IntPrimitive(this.max_date).write());
		
		return bOut.toByteArray();
    }
}
