//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ReceivedMessages extends TlObject {

    public static final int ID = 94983360;

    public int max_id;

    public ReceivedMessages(int max_id) {
        this.max_id = max_id;
    }

    public static ReceivedMessages read(ByteArrayInputStream bytes) throws IOException {
        int max_id = IntPrimitive.read(bytes).getValue();
		
		return new ReceivedMessages(max_id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new IntPrimitive(this.max_id).write());
		
		return bOut.toByteArray();
    }
}
