//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ReportReaction extends TlObject {

    public static final int ID = 1063567478;

    public TlObject peer;
	public int id;
	public TlObject reaction_peer;

    public ReportReaction(TlObject peer, int id, TlObject reaction_peer) {
        this.peer = peer;
		this.id = id;
		this.reaction_peer = reaction_peer;
    }

    public static ReportReaction read(ByteArrayInputStream bytes) throws IOException {
        TlObject peer = TlObject.read(bytes);
		int id = IntPrimitive.read(bytes).getValue();
		TlObject reaction_peer = TlObject.read(bytes);
		
		return new ReportReaction(peer, id, reaction_peer);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.peer.write());
		bOut.write(new IntPrimitive(this.id).write());
		bOut.write(this.reaction_peer.write());
		
		return bOut.toByteArray();
    }
}
