//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class RequestWebView extends TlObject {

    public static final int ID = 395003915;

    public boolean from_bot_menu;
	public boolean silent;
	public TlObject peer;
	public TlObject bot;
	public String url;
	public String start_param;
	public TlObject theme_params;
	public String platform;
	public int reply_to_msg_id;
	public int top_msg_id;
	public TlObject send_as;

    public RequestWebView(boolean from_bot_menu, boolean silent, TlObject peer, TlObject bot, String url, String start_param, TlObject theme_params, String platform, int reply_to_msg_id, int top_msg_id, TlObject send_as) {
        this.from_bot_menu = from_bot_menu;
		this.silent = silent;
		this.peer = peer;
		this.bot = bot;
		this.url = url;
		this.start_param = start_param;
		this.theme_params = theme_params;
		this.platform = platform;
		this.reply_to_msg_id = reply_to_msg_id;
		this.top_msg_id = top_msg_id;
		this.send_as = send_as;
    }

    public static RequestWebView read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean from_bot_menu = (flags & (1 << 4)) != 0;
		boolean silent = (flags & (1 << 5)) != 0;
		TlObject peer = TlObject.read(bytes);
		TlObject bot = TlObject.read(bytes);
		String url = (flags & (1 << 1)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		String start_param = (flags & (1 << 3)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		TlObject theme_params = (flags & (1 << 2)) != 0 ?  TlObject.read(bytes) : null;
		String platform = StringPrimitive.read(bytes).getValue();
		int reply_to_msg_id = (flags & (1 << 0)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		int top_msg_id = (flags & (1 << 9)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		TlObject send_as = (flags & (1 << 13)) != 0 ?  TlObject.read(bytes) : null;
		
		return new RequestWebView(from_bot_menu, silent, peer, bot, url, start_param, theme_params, platform, reply_to_msg_id, top_msg_id, send_as);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.from_bot_menu ? (1 << 4) : 0;
		flags |= this.silent ? (1 << 5) : 0;
		flags |= (this.url != null) ? (1 << 1) : 0;
		flags |= (this.start_param != null) ? (1 << 3) : 0;
		flags |= (this.theme_params != null) ? (1 << 2) : 0;
		flags |= (this.reply_to_msg_id != 0) ? (1 << 0) : 0;
		flags |= (this.top_msg_id != 0) ? (1 << 9) : 0;
		flags |= (this.send_as != null) ? (1 << 13) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(this.peer.write());
		bOut.write(this.bot.write());
		if(this.url != null)
			bOut.write(new StringPrimitive(this.url).write());
		if(this.start_param != null)
			bOut.write(new StringPrimitive(this.start_param).write());
		if(this.theme_params != null)
			bOut.write(this.theme_params.write());
		bOut.write(new StringPrimitive(this.platform).write());
		if(this.reply_to_msg_id != 0)
			bOut.write(new IntPrimitive(this.reply_to_msg_id).write());
		if(this.top_msg_id != 0)
			bOut.write(new IntPrimitive(this.top_msg_id).write());
		if(this.send_as != null)
			bOut.write(this.send_as.write());
		
		return bOut.toByteArray();
    }
}
