//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class RequestAppWebView extends TlObject {

    public static final int ID = -1940243652;

    public boolean write_allowed;
	public TlObject peer;
	public TlObject app;
	public String start_param;
	public TlObject theme_params;
	public String platform;

    public RequestAppWebView(boolean write_allowed, TlObject peer, TlObject app, String start_param, TlObject theme_params, String platform) {
        this.write_allowed = write_allowed;
		this.peer = peer;
		this.app = app;
		this.start_param = start_param;
		this.theme_params = theme_params;
		this.platform = platform;
    }

    public static RequestAppWebView read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean write_allowed = (flags & (1 << 0)) != 0;
		TlObject peer = TlObject.read(bytes);
		TlObject app = TlObject.read(bytes);
		String start_param = (flags & (1 << 1)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		TlObject theme_params = (flags & (1 << 2)) != 0 ?  TlObject.read(bytes) : null;
		String platform = StringPrimitive.read(bytes).getValue();
		
		return new RequestAppWebView(write_allowed, peer, app, start_param, theme_params, platform);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.write_allowed ? (1 << 0) : 0;
		flags |= (this.start_param != null) ? (1 << 1) : 0;
		flags |= (this.theme_params != null) ? (1 << 2) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(this.peer.write());
		bOut.write(this.app.write());
		if(this.start_param != null)
			bOut.write(new StringPrimitive(this.start_param).write());
		if(this.theme_params != null)
			bOut.write(this.theme_params.write());
		bOut.write(new StringPrimitive(this.platform).write());
		
		return bOut.toByteArray();
    }
}
