//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class SaveDraft extends TlObject {

    public static final int ID = -1271718337;

    public boolean no_webpage;
	public int reply_to_msg_id;
	public int top_msg_id;
	public TlObject peer;
	public String message;
	public ArrayList<TlObject> entities;

    public SaveDraft(boolean no_webpage, int reply_to_msg_id, int top_msg_id, TlObject peer, String message, ArrayList<TlObject> entities) {
        this.no_webpage = no_webpage;
		this.reply_to_msg_id = reply_to_msg_id;
		this.top_msg_id = top_msg_id;
		this.peer = peer;
		this.message = message;
		this.entities = entities;
    }

    public static SaveDraft read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean no_webpage = (flags & (1 << 1)) != 0;
		int reply_to_msg_id = (flags & (1 << 0)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		int top_msg_id = (flags & (1 << 2)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		TlObject peer = TlObject.read(bytes);
		String message = StringPrimitive.read(bytes).getValue();
		ArrayList<TlObject> entities = (flags & (1 << 3)) != 0 ?  ((VectorPrimitive)TlObject.read(bytes)).getValue() : null;
		
		return new SaveDraft(no_webpage, reply_to_msg_id, top_msg_id, peer, message, entities);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.no_webpage ? (1 << 1) : 0;
		flags |= (this.reply_to_msg_id != 0) ? (1 << 0) : 0;
		flags |= (this.top_msg_id != 0) ? (1 << 2) : 0;
		flags |= (this.entities != null) ? (1 << 3) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		if(this.reply_to_msg_id != 0)
			bOut.write(new IntPrimitive(this.reply_to_msg_id).write());
		if(this.top_msg_id != 0)
			bOut.write(new IntPrimitive(this.top_msg_id).write());
		bOut.write(this.peer.write());
		bOut.write(new StringPrimitive(this.message).write());
		if(this.entities != null)
			bOut.write(new VectorPrimitive(this.entities).write());
		
		return bOut.toByteArray();
    }
}
