//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class SaveDefaultSendAs extends TlObject {

    public static final int ID = -855777386;

    public TlObject peer;
	public TlObject send_as;

    public SaveDefaultSendAs(TlObject peer, TlObject send_as) {
        this.peer = peer;
		this.send_as = send_as;
    }

    public static SaveDefaultSendAs read(ByteArrayInputStream bytes) throws IOException {
        TlObject peer = TlObject.read(bytes);
		TlObject send_as = TlObject.read(bytes);
		
		return new SaveDefaultSendAs(peer, send_as);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.peer.write());
		bOut.write(this.send_as.write());
		
		return bOut.toByteArray();
    }
}
