//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class SearchStickerSets extends TlObject {

    public static final int ID = 896555914;

    public boolean exclude_featured;
	public String q;
	public long hash;

    public SearchStickerSets(boolean exclude_featured, String q, long hash) {
        this.exclude_featured = exclude_featured;
		this.q = q;
		this.hash = hash;
    }

    public static SearchStickerSets read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean exclude_featured = (flags & (1 << 0)) != 0;
		String q = StringPrimitive.read(bytes).getValue();
		long hash = LongPrimitive.read(bytes).getValue();
		
		return new SearchStickerSets(exclude_featured, q, hash);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.exclude_featured ? (1 << 0) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new StringPrimitive(this.q).write());
		bOut.write(new LongPrimitive(this.hash).write());
		
		return bOut.toByteArray();
    }
}
