//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class SendInlineBotResult extends TlObject {

    public static final int ID = -738468661;

    public boolean silent;
	public boolean background;
	public boolean clear_draft;
	public boolean hide_via;
	public TlObject peer;
	public int reply_to_msg_id;
	public int top_msg_id;
	public long random_id;
	public long query_id;
	public String id;
	public int schedule_date;
	public TlObject send_as;

    public SendInlineBotResult(boolean silent, boolean background, boolean clear_draft, boolean hide_via, TlObject peer, int reply_to_msg_id, int top_msg_id, long random_id, long query_id, String id, int schedule_date, TlObject send_as) {
        this.silent = silent;
		this.background = background;
		this.clear_draft = clear_draft;
		this.hide_via = hide_via;
		this.peer = peer;
		this.reply_to_msg_id = reply_to_msg_id;
		this.top_msg_id = top_msg_id;
		this.random_id = random_id;
		this.query_id = query_id;
		this.id = id;
		this.schedule_date = schedule_date;
		this.send_as = send_as;
    }

    public static SendInlineBotResult read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean silent = (flags & (1 << 5)) != 0;
		boolean background = (flags & (1 << 6)) != 0;
		boolean clear_draft = (flags & (1 << 7)) != 0;
		boolean hide_via = (flags & (1 << 11)) != 0;
		TlObject peer = TlObject.read(bytes);
		int reply_to_msg_id = (flags & (1 << 0)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		int top_msg_id = (flags & (1 << 9)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		long random_id = LongPrimitive.read(bytes).getValue();
		long query_id = LongPrimitive.read(bytes).getValue();
		String id = StringPrimitive.read(bytes).getValue();
		int schedule_date = (flags & (1 << 10)) != 0 ?  IntPrimitive.read(bytes).getValue() : 0;
		TlObject send_as = (flags & (1 << 13)) != 0 ?  TlObject.read(bytes) : null;
		
		return new SendInlineBotResult(silent, background, clear_draft, hide_via, peer, reply_to_msg_id, top_msg_id, random_id, query_id, id, schedule_date, send_as);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.silent ? (1 << 5) : 0;
		flags |= this.background ? (1 << 6) : 0;
		flags |= this.clear_draft ? (1 << 7) : 0;
		flags |= this.hide_via ? (1 << 11) : 0;
		flags |= (this.reply_to_msg_id != 0) ? (1 << 0) : 0;
		flags |= (this.top_msg_id != 0) ? (1 << 9) : 0;
		flags |= (this.schedule_date != 0) ? (1 << 10) : 0;
		flags |= (this.send_as != null) ? (1 << 13) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(this.peer.write());
		if(this.reply_to_msg_id != 0)
			bOut.write(new IntPrimitive(this.reply_to_msg_id).write());
		if(this.top_msg_id != 0)
			bOut.write(new IntPrimitive(this.top_msg_id).write());
		bOut.write(new LongPrimitive(this.random_id).write());
		bOut.write(new LongPrimitive(this.query_id).write());
		bOut.write(new StringPrimitive(this.id).write());
		if(this.schedule_date != 0)
			bOut.write(new IntPrimitive(this.schedule_date).write());
		if(this.send_as != null)
			bOut.write(this.send_as.write());
		
		return bOut.toByteArray();
    }
}
