//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class SetBotShippingResults extends TlObject {

    public static final int ID = -436833542;

    public long query_id;
	public String error;
	public ArrayList<TlObject> shipping_options;

    public SetBotShippingResults(long query_id, String error, ArrayList<TlObject> shipping_options) {
        this.query_id = query_id;
		this.error = error;
		this.shipping_options = shipping_options;
    }

    public static SetBotShippingResults read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		long query_id = LongPrimitive.read(bytes).getValue();
		String error = (flags & (1 << 0)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		ArrayList<TlObject> shipping_options = (flags & (1 << 1)) != 0 ?  ((VectorPrimitive)TlObject.read(bytes)).getValue() : null;
		
		return new SetBotShippingResults(query_id, error, shipping_options);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= (this.error != null) ? (1 << 0) : 0;
		flags |= (this.shipping_options != null) ? (1 << 1) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new LongPrimitive(this.query_id).write());
		if(this.error != null)
			bOut.write(new StringPrimitive(this.error).write());
		if(this.shipping_options != null)
			bOut.write(new VectorPrimitive(this.shipping_options).write());
		
		return bOut.toByteArray();
    }
}
