//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class SetChatTheme extends TlObject {

    public static final int ID = -432283329;

    public TlObject peer;
	public String emoticon;

    public SetChatTheme(TlObject peer, String emoticon) {
        this.peer = peer;
		this.emoticon = emoticon;
    }

    public static SetChatTheme read(ByteArrayInputStream bytes) throws IOException {
        TlObject peer = TlObject.read(bytes);
		String emoticon = StringPrimitive.read(bytes).getValue();
		
		return new SetChatTheme(peer, emoticon);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.peer.write());
		bOut.write(new StringPrimitive(this.emoticon).write());
		
		return bOut.toByteArray();
    }
}
