//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class SetInlineBotResults extends TlObject {

    public static final int ID = -1156406247;

    public boolean gallery;
	public boolean privatev;
	public long query_id;
	public ArrayList<TlObject> results;
	public int cache_time;
	public String next_offset;
	public TlObject switch_pm;
	public TlObject switch_webview;

    public SetInlineBotResults(boolean gallery, boolean privatev, long query_id, ArrayList<TlObject> results, int cache_time, String next_offset, TlObject switch_pm, TlObject switch_webview) {
        this.gallery = gallery;
		this.privatev = privatev;
		this.query_id = query_id;
		this.results = results;
		this.cache_time = cache_time;
		this.next_offset = next_offset;
		this.switch_pm = switch_pm;
		this.switch_webview = switch_webview;
    }

    public static SetInlineBotResults read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean gallery = (flags & (1 << 0)) != 0;
		boolean privatev = (flags & (1 << 1)) != 0;
		long query_id = LongPrimitive.read(bytes).getValue();
		ArrayList<TlObject> results = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		int cache_time = IntPrimitive.read(bytes).getValue();
		String next_offset = (flags & (1 << 2)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		TlObject switch_pm = (flags & (1 << 3)) != 0 ?  TlObject.read(bytes) : null;
		TlObject switch_webview = (flags & (1 << 4)) != 0 ?  TlObject.read(bytes) : null;
		
		return new SetInlineBotResults(gallery, privatev, query_id, results, cache_time, next_offset, switch_pm, switch_webview);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.gallery ? (1 << 0) : 0;
		flags |= this.privatev ? (1 << 1) : 0;
		flags |= (this.next_offset != null) ? (1 << 2) : 0;
		flags |= (this.switch_pm != null) ? (1 << 3) : 0;
		flags |= (this.switch_webview != null) ? (1 << 4) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new LongPrimitive(this.query_id).write());
		bOut.write(new VectorPrimitive(this.results).write());
		bOut.write(new IntPrimitive(this.cache_time).write());
		if(this.next_offset != null)
			bOut.write(new StringPrimitive(this.next_offset).write());
		if(this.switch_pm != null)
			bOut.write(this.switch_pm.write());
		if(this.switch_webview != null)
			bOut.write(this.switch_webview.write());
		
		return bOut.toByteArray();
    }
}
