//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.messages;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class StartHistoryImport extends TlObject {

    public static final int ID = -1271008444;

    public TlObject peer;
	public long import_id;

    public StartHistoryImport(TlObject peer, long import_id) {
        this.peer = peer;
		this.import_id = import_id;
    }

    public static StartHistoryImport read(ByteArrayInputStream bytes) throws IOException {
        TlObject peer = TlObject.read(bytes);
		long import_id = LongPrimitive.read(bytes).getValue();
		
		return new StartHistoryImport(peer, import_id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.peer.write());
		bOut.write(new LongPrimitive(this.import_id).write());
		
		return bOut.toByteArray();
    }
}
