//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.stats;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class GetMessageStats extends TlObject {

    public static final int ID = -1226791947;

    public boolean dark;
	public TlObject channel;
	public int msg_id;

    public GetMessageStats(boolean dark, TlObject channel, int msg_id) {
        this.dark = dark;
		this.channel = channel;
		this.msg_id = msg_id;
    }

    public static GetMessageStats read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean dark = (flags & (1 << 0)) != 0;
		TlObject channel = TlObject.read(bytes);
		int msg_id = IntPrimitive.read(bytes).getValue();
		
		return new GetMessageStats(dark, channel, msg_id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.dark ? (1 << 0) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(this.channel.write());
		bOut.write(new IntPrimitive(this.msg_id).write());
		
		return bOut.toByteArray();
    }
}
