//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.stats;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class LoadAsyncGraph extends TlObject {

    public static final int ID = 1646092192;

    public String token;
	public long x;

    public LoadAsyncGraph(String token, long x) {
        this.token = token;
		this.x = x;
    }

    public static LoadAsyncGraph read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		String token = StringPrimitive.read(bytes).getValue();
		long x = (flags & (1 << 0)) != 0 ?  LongPrimitive.read(bytes).getValue() : 0;
		
		return new LoadAsyncGraph(token, x);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= (this.x != 0) ? (1 << 0) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new StringPrimitive(this.token).write());
		if(this.x != 0)
			bOut.write(new LongPrimitive(this.x).write());
		
		return bOut.toByteArray();
    }
}
