//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.bots;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class AnswerWebhookJSONQuery extends TlObject {

    public static final int ID = -434028723;

    public long query_id;
	public TlObject data;

    public AnswerWebhookJSONQuery(long query_id, TlObject data) {
        this.query_id = query_id;
		this.data = data;
    }

    public static AnswerWebhookJSONQuery read(ByteArrayInputStream bytes) throws IOException {
        long query_id = LongPrimitive.read(bytes).getValue();
		TlObject data = TlObject.read(bytes);
		
		return new AnswerWebhookJSONQuery(query_id, data);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new LongPrimitive(this.query_id).write());
		bOut.write(this.data.write());
		
		return bOut.toByteArray();
    }
}
