//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.bots;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class SetBotCommands extends TlObject {

    public static final int ID = 85399130;

    public TlObject scope;
	public String lang_code;
	public ArrayList<TlObject> commands;

    public SetBotCommands(TlObject scope, String lang_code, ArrayList<TlObject> commands) {
        this.scope = scope;
		this.lang_code = lang_code;
		this.commands = commands;
    }

    public static SetBotCommands read(ByteArrayInputStream bytes) throws IOException {
        TlObject scope = TlObject.read(bytes);
		String lang_code = StringPrimitive.read(bytes).getValue();
		ArrayList<TlObject> commands = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		
		return new SetBotCommands(scope, lang_code, commands);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.scope.write());
		bOut.write(new StringPrimitive(this.lang_code).write());
		bOut.write(new VectorPrimitive(this.commands).write());
		
		return bOut.toByteArray();
    }
}
