//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.stickers;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class DeleteStickerSet extends TlObject {

    public static final int ID = -2022685804;

    public TlObject stickerset;

    public DeleteStickerSet(TlObject stickerset) {
        this.stickerset = stickerset;
    }

    public static DeleteStickerSet read(ByteArrayInputStream bytes) throws IOException {
        TlObject stickerset = TlObject.read(bytes);
		
		return new DeleteStickerSet(stickerset);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.stickerset.write());
		
		return bOut.toByteArray();
    }
}
