//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.stickers;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class RemoveStickerFromSet extends TlObject {

    public static final int ID = -143257775;

    public TlObject sticker;

    public RemoveStickerFromSet(TlObject sticker) {
        this.sticker = sticker;
    }

    public static RemoveStickerFromSet read(ByteArrayInputStream bytes) throws IOException {
        TlObject sticker = TlObject.read(bytes);
		
		return new RemoveStickerFromSet(sticker);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.sticker.write());
		
		return bOut.toByteArray();
    }
}
