//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.phone;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class GetGroupCall extends TlObject {

    public static final int ID = 68699611;

    public TlObject call;
	public int limit;

    public GetGroupCall(TlObject call, int limit) {
        this.call = call;
		this.limit = limit;
    }

    public static GetGroupCall read(ByteArrayInputStream bytes) throws IOException {
        TlObject call = TlObject.read(bytes);
		int limit = IntPrimitive.read(bytes).getValue();
		
		return new GetGroupCall(call, limit);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.call.write());
		bOut.write(new IntPrimitive(this.limit).write());
		
		return bOut.toByteArray();
    }
}
