//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.phone;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class SendSignalingData extends TlObject {

    public static final int ID = -8744061;

    public TlObject peer;
	public byte[] data;

    public SendSignalingData(TlObject peer, byte[] data) {
        this.peer = peer;
		this.data = data;
    }

    public static SendSignalingData read(ByteArrayInputStream bytes) throws IOException {
        TlObject peer = TlObject.read(bytes);
		byte[] data = BytesPrimitive.read(bytes).getValue();
		
		return new SendSignalingData(peer, data);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.peer.write());
		bOut.write(new BytesPrimitive(this.data).write());
		
		return bOut.toByteArray();
    }
}
