//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.phone;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class StartScheduledGroupCall extends TlObject {

    public static final int ID = 1451287362;

    public TlObject call;

    public StartScheduledGroupCall(TlObject call) {
        this.call = call;
    }

    public static StartScheduledGroupCall read(ByteArrayInputStream bytes) throws IOException {
        TlObject call = TlObject.read(bytes);
		
		return new StartScheduledGroupCall(call);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.call.write());
		
		return bOut.toByteArray();
    }
}
