//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.auth;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ExportAuthorization extends TlObject {

    public static final int ID = -440401971;

    public int dc_id;

    public ExportAuthorization(int dc_id) {
        this.dc_id = dc_id;
    }

    public static ExportAuthorization read(ByteArrayInputStream bytes) throws IOException {
        int dc_id = IntPrimitive.read(bytes).getValue();
		
		return new ExportAuthorization(dc_id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new IntPrimitive(this.dc_id).write());
		
		return bOut.toByteArray();
    }
}
