//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.auth;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ImportLoginToken extends TlObject {

    public static final int ID = -1783866140;

    public byte[] token;

    public ImportLoginToken(byte[] token) {
        this.token = token;
    }

    public static ImportLoginToken read(ByteArrayInputStream bytes) throws IOException {
        byte[] token = BytesPrimitive.read(bytes).getValue();
		
		return new ImportLoginToken(token);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new BytesPrimitive(this.token).write());
		
		return bOut.toByteArray();
    }
}
