//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.auth;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ResendCode extends TlObject {

    public static final int ID = 1056025023;

    public String phone_number;
	public String phone_code_hash;

    public ResendCode(String phone_number, String phone_code_hash) {
        this.phone_number = phone_number;
		this.phone_code_hash = phone_code_hash;
    }

    public static ResendCode read(ByteArrayInputStream bytes) throws IOException {
        String phone_number = StringPrimitive.read(bytes).getValue();
		String phone_code_hash = StringPrimitive.read(bytes).getValue();
		
		return new ResendCode(phone_number, phone_code_hash);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new StringPrimitive(this.phone_number).write());
		bOut.write(new StringPrimitive(this.phone_code_hash).write());
		
		return bOut.toByteArray();
    }
}
