//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.auth;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class SendCode extends TlObject {

    public static final int ID = -1502141361;

    public String phone_number;
	public int api_id;
	public String api_hash;
	public TlObject settings;

    public SendCode(String phone_number, int api_id, String api_hash, TlObject settings) {
        this.phone_number = phone_number;
		this.api_id = api_id;
		this.api_hash = api_hash;
		this.settings = settings;
    }

    public static SendCode read(ByteArrayInputStream bytes) throws IOException {
        String phone_number = StringPrimitive.read(bytes).getValue();
		int api_id = IntPrimitive.read(bytes).getValue();
		String api_hash = StringPrimitive.read(bytes).getValue();
		TlObject settings = TlObject.read(bytes);
		
		return new SendCode(phone_number, api_id, api_hash, settings);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new StringPrimitive(this.phone_number).write());
		bOut.write(new IntPrimitive(this.api_id).write());
		bOut.write(new StringPrimitive(this.api_hash).write());
		bOut.write(this.settings.write());
		
		return bOut.toByteArray();
    }
}
