//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.channels;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class DeleteTopicHistory extends TlObject {

    public static final int ID = 876830509;

    public TlObject channel;
	public int top_msg_id;

    public DeleteTopicHistory(TlObject channel, int top_msg_id) {
        this.channel = channel;
		this.top_msg_id = top_msg_id;
    }

    public static DeleteTopicHistory read(ByteArrayInputStream bytes) throws IOException {
        TlObject channel = TlObject.read(bytes);
		int top_msg_id = IntPrimitive.read(bytes).getValue();
		
		return new DeleteTopicHistory(channel, top_msg_id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.channel.write());
		bOut.write(new IntPrimitive(this.top_msg_id).write());
		
		return bOut.toByteArray();
    }
}
