//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.channels;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class GetMessages extends TlObject {

    public static final int ID = -1383294429;

    public TlObject channel;
	public ArrayList<TlObject> id;

    public GetMessages(TlObject channel, ArrayList<TlObject> id) {
        this.channel = channel;
		this.id = id;
    }

    public static GetMessages read(ByteArrayInputStream bytes) throws IOException {
        TlObject channel = TlObject.read(bytes);
		ArrayList<TlObject> id = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		
		return new GetMessages(channel, id);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.channel.write());
		bOut.write(new VectorPrimitive(this.id).write());
		
		return bOut.toByteArray();
    }
}
