//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.folders;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class EditPeerFolders extends TlObject {

    public static final int ID = 1749536939;

    public ArrayList<TlObject> folder_peers;

    public EditPeerFolders(ArrayList<TlObject> folder_peers) {
        this.folder_peers = folder_peers;
    }

    public static EditPeerFolders read(ByteArrayInputStream bytes) throws IOException {
        ArrayList<TlObject> folder_peers = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		
		return new EditPeerFolders(folder_peers);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new VectorPrimitive(this.folder_peers).write());
		
		return bOut.toByteArray();
    }
}
