//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.account;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ConfirmPhone extends TlObject {

    public static final int ID = 1596029123;

    public String phone_code_hash;
	public String phone_code;

    public ConfirmPhone(String phone_code_hash, String phone_code) {
        this.phone_code_hash = phone_code_hash;
		this.phone_code = phone_code;
    }

    public static ConfirmPhone read(ByteArrayInputStream bytes) throws IOException {
        String phone_code_hash = StringPrimitive.read(bytes).getValue();
		String phone_code = StringPrimitive.read(bytes).getValue();
		
		return new ConfirmPhone(phone_code_hash, phone_code);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new StringPrimitive(this.phone_code_hash).write());
		bOut.write(new StringPrimitive(this.phone_code).write());
		
		return bOut.toByteArray();
    }
}
