//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.account;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class FinishTakeoutSession extends TlObject {

    public static final int ID = 489050862;

    public boolean success;

    public FinishTakeoutSession(boolean success) {
        this.success = success;
    }

    public static FinishTakeoutSession read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean success = (flags & (1 << 0)) != 0;
		
		return new FinishTakeoutSession(success);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.success ? (1 << 0) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		
		return bOut.toByteArray();
    }
}
