//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.account;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class GetTheme extends TlObject {

    public static final int ID = 978872812;

    public String format;
	public TlObject theme;

    public GetTheme(String format, TlObject theme) {
        this.format = format;
		this.theme = theme;
    }

    public static GetTheme read(ByteArrayInputStream bytes) throws IOException {
        String format = StringPrimitive.read(bytes).getValue();
		TlObject theme = TlObject.read(bytes);
		
		return new GetTheme(format, theme);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new StringPrimitive(this.format).write());
		bOut.write(this.theme.write());
		
		return bOut.toByteArray();
    }
}
