//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.account;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class RegisterDevice extends TlObject {

    public static final int ID = -326762118;

    public boolean no_muted;
	public int token_type;
	public String token;
	public TlObject app_sandbox;
	public byte[] secret;
	public ArrayList<TlObject> other_uids;

    public RegisterDevice(boolean no_muted, int token_type, String token, TlObject app_sandbox, byte[] secret, ArrayList<TlObject> other_uids) {
        this.no_muted = no_muted;
		this.token_type = token_type;
		this.token = token;
		this.app_sandbox = app_sandbox;
		this.secret = secret;
		this.other_uids = other_uids;
    }

    public static RegisterDevice read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean no_muted = (flags & (1 << 0)) != 0;
		int token_type = IntPrimitive.read(bytes).getValue();
		String token = StringPrimitive.read(bytes).getValue();
		TlObject app_sandbox = TlObject.read(bytes);
		byte[] secret = BytesPrimitive.read(bytes).getValue();
		ArrayList<TlObject> other_uids = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		
		return new RegisterDevice(no_muted, token_type, token, app_sandbox, secret, other_uids);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.no_muted ? (1 << 0) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new IntPrimitive(this.token_type).write());
		bOut.write(new StringPrimitive(this.token).write());
		bOut.write(this.app_sandbox.write());
		bOut.write(new BytesPrimitive(this.secret).write());
		bOut.write(new VectorPrimitive(this.other_uids).write());
		
		return bOut.toByteArray();
    }
}
