//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.account;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class SaveRingtone extends TlObject {

    public static final int ID = 1038768899;

    public TlObject id;
	public TlObject unsave;

    public SaveRingtone(TlObject id, TlObject unsave) {
        this.id = id;
		this.unsave = unsave;
    }

    public static SaveRingtone read(ByteArrayInputStream bytes) throws IOException {
        TlObject id = TlObject.read(bytes);
		TlObject unsave = TlObject.read(bytes);
		
		return new SaveRingtone(id, unsave);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.id.write());
		bOut.write(this.unsave.write());
		
		return bOut.toByteArray();
    }
}
