//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.account;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class SendVerifyPhoneCode extends TlObject {

    public static final int ID = -1516022023;

    public String phone_number;
	public TlObject settings;

    public SendVerifyPhoneCode(String phone_number, TlObject settings) {
        this.phone_number = phone_number;
		this.settings = settings;
    }

    public static SendVerifyPhoneCode read(ByteArrayInputStream bytes) throws IOException {
        String phone_number = StringPrimitive.read(bytes).getValue();
		TlObject settings = TlObject.read(bytes);
		
		return new SendVerifyPhoneCode(phone_number, settings);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new StringPrimitive(this.phone_number).write());
		bOut.write(this.settings.write());
		
		return bOut.toByteArray();
    }
}
