//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.account;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class SendVerifyEmailCode extends TlObject {

    public static final int ID = -1730136133;

    public TlObject purpose;
	public String email;

    public SendVerifyEmailCode(TlObject purpose, String email) {
        this.purpose = purpose;
		this.email = email;
    }

    public static SendVerifyEmailCode read(ByteArrayInputStream bytes) throws IOException {
        TlObject purpose = TlObject.read(bytes);
		String email = StringPrimitive.read(bytes).getValue();
		
		return new SendVerifyEmailCode(purpose, email);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.purpose.write());
		bOut.write(new StringPrimitive(this.email).write());
		
		return bOut.toByteArray();
    }
}
