//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.account;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class SetContentSettings extends TlObject {

    public static final int ID = -1250643605;

    public boolean sensitive_enabled;

    public SetContentSettings(boolean sensitive_enabled) {
        this.sensitive_enabled = sensitive_enabled;
    }

    public static SetContentSettings read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		boolean sensitive_enabled = (flags & (1 << 0)) != 0;
		
		return new SetContentSettings(sensitive_enabled);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= this.sensitive_enabled ? (1 << 0) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		
		return bOut.toByteArray();
    }
}
