//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.account;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ToggleUsername extends TlObject {

    public static final int ID = 1490465654;

    public String username;
	public TlObject active;

    public ToggleUsername(String username, TlObject active) {
        this.username = username;
		this.active = active;
    }

    public static ToggleUsername read(ByteArrayInputStream bytes) throws IOException {
        String username = StringPrimitive.read(bytes).getValue();
		TlObject active = TlObject.read(bytes);
		
		return new ToggleUsername(username, active);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new StringPrimitive(this.username).write());
		bOut.write(this.active.write());
		
		return bOut.toByteArray();
    }
}
