//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.account;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UpdateUsername extends TlObject {

    public static final int ID = 1040964988;

    public String username;

    public UpdateUsername(String username) {
        this.username = username;
    }

    public static UpdateUsername read(ByteArrayInputStream bytes) throws IOException {
        String username = StringPrimitive.read(bytes).getValue();
		
		return new UpdateUsername(username);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new StringPrimitive(this.username).write());
		
		return bOut.toByteArray();
    }
}
