//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.account;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UpdateProfile extends TlObject {

    public static final int ID = 2018596725;

    public String first_name;
	public String last_name;
	public String about;

    public UpdateProfile(String first_name, String last_name, String about) {
        this.first_name = first_name;
		this.last_name = last_name;
		this.about = about;
    }

    public static UpdateProfile read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		String first_name = (flags & (1 << 0)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		String last_name = (flags & (1 << 1)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		String about = (flags & (1 << 2)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		
		return new UpdateProfile(first_name, last_name, about);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= (this.first_name != null) ? (1 << 0) : 0;
		flags |= (this.last_name != null) ? (1 << 1) : 0;
		flags |= (this.about != null) ? (1 << 2) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		if(this.first_name != null)
			bOut.write(new StringPrimitive(this.first_name).write());
		if(this.last_name != null)
			bOut.write(new StringPrimitive(this.last_name).write());
		if(this.about != null)
			bOut.write(new StringPrimitive(this.about).write());
		
		return bOut.toByteArray();
    }
}
