//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.account;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UpdateStatus extends TlObject {

    public static final int ID = 1713919532;

    public TlObject offline;

    public UpdateStatus(TlObject offline) {
        this.offline = offline;
    }

    public static UpdateStatus read(ByteArrayInputStream bytes) throws IOException {
        TlObject offline = TlObject.read(bytes);
		
		return new UpdateStatus(offline);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.offline.write());
		
		return bOut.toByteArray();
    }
}
