//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.account;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UpdateEmojiStatus extends TlObject {

    public static final int ID = -70001045;

    public TlObject emoji_status;

    public UpdateEmojiStatus(TlObject emoji_status) {
        this.emoji_status = emoji_status;
    }

    public static UpdateEmojiStatus read(ByteArrayInputStream bytes) throws IOException {
        TlObject emoji_status = TlObject.read(bytes);
		
		return new UpdateEmojiStatus(emoji_status);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.emoji_status.write());
		
		return bOut.toByteArray();
    }
}
