//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.account;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class UpdateTheme extends TlObject {

    public static final int ID = 737414348;

    public String format;
	public TlObject theme;
	public String slug;
	public String title;
	public TlObject document;
	public ArrayList<TlObject> settings;

    public UpdateTheme(String format, TlObject theme, String slug, String title, TlObject document, ArrayList<TlObject> settings) {
        this.format = format;
		this.theme = theme;
		this.slug = slug;
		this.title = title;
		this.document = document;
		this.settings = settings;
    }

    public static UpdateTheme read(ByteArrayInputStream bytes) throws IOException {
        int flags = IntPrimitive.read(bytes).getValue();
		String format = StringPrimitive.read(bytes).getValue();
		TlObject theme = TlObject.read(bytes);
		String slug = (flags & (1 << 0)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		String title = (flags & (1 << 1)) != 0 ?  StringPrimitive.read(bytes).getValue() : null;
		TlObject document = (flags & (1 << 2)) != 0 ?  TlObject.read(bytes) : null;
		ArrayList<TlObject> settings = (flags & (1 << 3)) != 0 ?  ((VectorPrimitive)TlObject.read(bytes)).getValue() : null;
		
		return new UpdateTheme(format, theme, slug, title, document, settings);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		int flags = 0;
		flags |= (this.slug != null) ? (1 << 0) : 0;
		flags |= (this.title != null) ? (1 << 1) : 0;
		flags |= (this.document != null) ? (1 << 2) : 0;
		flags |= (this.settings != null) ? (1 << 3) : 0;
		
		
		bOut.write(new IntPrimitive(flags).write());
		bOut.write(new StringPrimitive(this.format).write());
		bOut.write(this.theme.write());
		if(this.slug != null)
			bOut.write(new StringPrimitive(this.slug).write());
		if(this.title != null)
			bOut.write(new StringPrimitive(this.title).write());
		if(this.document != null)
			bOut.write(this.document.write());
		if(this.settings != null)
			bOut.write(new VectorPrimitive(this.settings).write());
		
		return bOut.toByteArray();
    }
}
