//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.photos;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class GetUserPhotos extends TlObject {

    public static final int ID = -1848823128;

    public TlObject user_id;
	public int offset;
	public long max_id;
	public int limit;

    public GetUserPhotos(TlObject user_id, int offset, long max_id, int limit) {
        this.user_id = user_id;
		this.offset = offset;
		this.max_id = max_id;
		this.limit = limit;
    }

    public static GetUserPhotos read(ByteArrayInputStream bytes) throws IOException {
        TlObject user_id = TlObject.read(bytes);
		int offset = IntPrimitive.read(bytes).getValue();
		long max_id = LongPrimitive.read(bytes).getValue();
		int limit = IntPrimitive.read(bytes).getValue();
		
		return new GetUserPhotos(user_id, offset, max_id, limit);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.user_id.write());
		bOut.write(new IntPrimitive(this.offset).write());
		bOut.write(new LongPrimitive(this.max_id).write());
		bOut.write(new IntPrimitive(this.limit).write());
		
		return bOut.toByteArray();
    }
}
