//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.upload;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class SaveBigFilePart extends TlObject {

    public static final int ID = -562337987;

    public long file_id;
	public int file_part;
	public int file_total_parts;
	public byte[] bytesv;

    public SaveBigFilePart(long file_id, int file_part, int file_total_parts, byte[] bytesv) {
        this.file_id = file_id;
		this.file_part = file_part;
		this.file_total_parts = file_total_parts;
		this.bytesv = bytesv;
    }

    public static SaveBigFilePart read(ByteArrayInputStream bytes) throws IOException {
        long file_id = LongPrimitive.read(bytes).getValue();
		int file_part = IntPrimitive.read(bytes).getValue();
		int file_total_parts = IntPrimitive.read(bytes).getValue();
		byte[] bytesv = BytesPrimitive.read(bytes).getValue();
		
		return new SaveBigFilePart(file_id, file_part, file_total_parts, bytesv);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new LongPrimitive(this.file_id).write());
		bOut.write(new IntPrimitive(this.file_part).write());
		bOut.write(new IntPrimitive(this.file_total_parts).write());
		bOut.write(new BytesPrimitive(this.bytesv).write());
		
		return bOut.toByteArray();
    }
}
