//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.payments;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class ExportInvoice extends TlObject {

    public static final int ID = 261206117;

    public TlObject invoice_media;

    public ExportInvoice(TlObject invoice_media) {
        this.invoice_media = invoice_media;
    }

    public static ExportInvoice read(ByteArrayInputStream bytes) throws IOException {
        TlObject invoice_media = TlObject.read(bytes);
		
		return new ExportInvoice(invoice_media);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.invoice_media.write());
		
		return bOut.toByteArray();
    }
}
