//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.help;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class EditUserInfo extends TlObject {

    public static final int ID = 1723407216;

    public TlObject user_id;
	public String message;
	public ArrayList<TlObject> entities;

    public EditUserInfo(TlObject user_id, String message, ArrayList<TlObject> entities) {
        this.user_id = user_id;
		this.message = message;
		this.entities = entities;
    }

    public static EditUserInfo read(ByteArrayInputStream bytes) throws IOException {
        TlObject user_id = TlObject.read(bytes);
		String message = StringPrimitive.read(bytes).getValue();
		ArrayList<TlObject> entities = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		
		return new EditUserInfo(user_id, message, entities);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.user_id.write());
		bOut.write(new StringPrimitive(this.message).write());
		bOut.write(new VectorPrimitive(this.entities).write());
		
		return bOut.toByteArray();
    }
}
