//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.chatlists;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class DeleteExportedInvite extends TlObject {

    public static final int ID = 1906072670;

    public TlObject chatlist;
	public String slug;

    public DeleteExportedInvite(TlObject chatlist, String slug) {
        this.chatlist = chatlist;
		this.slug = slug;
    }

    public static DeleteExportedInvite read(ByteArrayInputStream bytes) throws IOException {
        TlObject chatlist = TlObject.read(bytes);
		String slug = StringPrimitive.read(bytes).getValue();
		
		return new DeleteExportedInvite(chatlist, slug);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(this.chatlist.write());
		bOut.write(new StringPrimitive(this.slug).write());
		
		return bOut.toByteArray();
    }
}
