//this is an autogenerated file!!
//!!!!!!!!!!
package telegram.raw.functions.chatlists;

import telegram.raw.core.TlObject;
import telegram.raw.core.primitives.BytesPrimitive;
import telegram.raw.core.primitives.StringPrimitive;
import telegram.raw.core.primitives.VectorPrimitive;
import telegram.raw.core.primitives.integers.IntPrimitive;
import telegram.raw.core.primitives.integers.LongPrimitive;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class JoinChatlistInvite extends TlObject {

    public static final int ID = -1498291302;

    public String slug;
	public ArrayList<TlObject> peers;

    public JoinChatlistInvite(String slug, ArrayList<TlObject> peers) {
        this.slug = slug;
		this.peers = peers;
    }

    public static JoinChatlistInvite read(ByteArrayInputStream bytes) throws IOException {
        String slug = StringPrimitive.read(bytes).getValue();
		ArrayList<TlObject> peers = ((VectorPrimitive)TlObject.read(bytes)).getValue();
		
		return new JoinChatlistInvite(slug, peers);
    }

    @Override
    public byte[] write() throws IOException {
        ByteArrayOutputStream bOut = new ByteArrayOutputStream();
		
		bOut.write(new IntPrimitive(ID).write());
		
		
		bOut.write(new StringPrimitive(this.slug).write());
		bOut.write(new VectorPrimitive(this.peers).write());
		
		return bOut.toByteArray();
    }
}
